/* =====================================================================
   LAS HIERBAS QUE CRECEN EN EL SERVIDOR — corpus.js
   el material compilado. cinco frecuencias. cada archivo es un documento
   con su régimen de verdad.

   estructura de cada archivo:
     { id, nombre, tipo, icono, peso, cuerpo, margenes, bloqueado }
   cuerpo:    el texto limpio
   margenes:  array de { texto, autor } — las anotaciones al margen
   bloqueado: si es true, requiere haber abierto otro archivo antes
   ===================================================================== */

window.HIERBAS = (function () {
  "use strict";

  var archivos = [

  /* ===================================================================
     FRECUENCIA 1: LOS LOGS DEL SERVIDOR
     fuente: exportación no autorizada, memoria USB
     régimen de verdad: automático. no miente porque no sabe mentir.
     =================================================================== */

  {
    id: "logs",
    nombre: "logs_servidor.txt",
    tipo: "frecuencia-1",
    icono: "⬡",
    peso: "12 KB",
    cuerpo: [
      "[WARN] 03:17:44 — rack14.vent: flujo de aire desviado 2.3% del nominal.",
      "  Causa probable: obstrucción física.",
      "  Acción recomendada: inspección visual del pasillo de refrigeración.",
      "",
      "[INFO] 06:02:11 — rack14.hum: humedad relativa 48.2% (+3.1% sobre media del pasillo).",
      "  Causa probable: condensación en junta minisplit7.",
      "  Acción recomendada: mantenimiento programado.",
      "",
      "[WARN] 06:02:12 — rack14.hum: la junta minisplit7 fue reportada en 2019. no se ha cambiado.",
      "  La anomalía actual no es atribuible a la junta.",
      "  No hay causa probable en la base de datos.",
      "  Clasificación: sin clasificar.",
      "",
      "[WARN] 12:44:08 — rack14.temp: +2.1°C sobre nominal.",
      "  Causa probable: ventilador trasero obstruido.",
      "  Nota: el ventilador no está obstruido. la temperatura sube sin causa.",
      "",
      "[WARN] 14:08:22 — rack14.vent: flujo de aire desviado 2.8% del nominal.",
      "  La desviación aumenta 0.5% cada 14 días.",
      "  El sistema no encuentra patrón.",
      "",
      "[INFO] 22:03:41 — rack22.temp: anomalía no clasificada.",
      "  Temperatura +1.4°C sobre nominal. Sin causa identificada.",
      "  El rack 22 no tiene ventilador obstruido.",
      "  El rack 22 no tiene junta dañada.",
      "  El rack 22 no debería estar caliente.",
      "",
      "[CRITICAL] 08:14:22 — rack31.temp: +4.8°C sobre nominal.",
      "  Causa probable: obstrucción de flujo de aire.",
      "  Acción recomendada: inspección visual inmediata.",
      "  Nota: inspección visual del 03/08 retiró material vegetal del rack 31.",
      "  La anomalía persiste después de la limpieza.",
      "  La anomalía no es atribuible a material vegetal retirado.",
      "  No hay causa probable en la base de datos.",
      "",
      "[CRITICAL] 09:02:17 — múltiples racks: anomalías de temperatura en racks 03, 08, 14, 15,",
      "  19, 22, 27, 31, y cuarto de UPS.",
      "  Patrón no reconocido.",
      "  Acción recomendada: fumigación externa.",
      "",
      "[INFO] 11:55:01 — fumigación completada. racks 03-31.",
      "  Producto: Clorotalonil 40%.",
      "  Resultado preliminar: material vegetal eliminado en superficie.",
      "  Monitoreo continuo programado.",
      "",
      "[WARN] 28:09:14 — rack14.temp: +2.2°C sobre nominal.",
      "  La anomalía reapareció 17 días después de la fumigación.",
      "  El material vegetal no fue eliminado.",
      "  Clasificación: sin clasificar."
    ],
    margenes: [
      { texto: "el sistema describe lo que no entiende con el lenguaje que tiene. \n' sin clasificar' es su forma de decir 'no sé qué es esto pero está vivo.'", autor: "compilador" }
    ]
  },

  /* ===================================================================
     FRECUENCIA 2: LOS POST-ITS
     fuente: 47 notas manuscritas, escaneadas
     régimen de verdad: subjetivo. miente por omisión.
     =================================================================== */

  {
    id: "postits",
    nombre: "postits.txt",
    tipo: "frecuencia-2",
    icono: "□",
    peso: "3 KB",
    cuerpo: [
      "dic 14 — 4 cm. dos frondas. pálida.",
      "dic 28 — 5 cm. tres frondas.",
      "",
      "ene 14 — 7 cm. la nueva tiene una mancha café.",
      "ene 28 — 7 cm. cuatro frondas. la mancha sigue.",
      "",
      "feb 14 — la mancha desapareció. no sé si se curó sola.",
      "feb 28 — 8 cm. cinco frondas. se inclina.",
      "",
      "mar 02 — 9 cm. se inclina hacia el led del blade B.",
      "         no le sirve pero no lo sabe.",
      "mar 16 — 10 cm. la inclinación es de 23°.",
      "         la medí con el transportador de mi hija.",
      "mar 30 — 10 cm. la inclinación cambió. ahora son 27°.",
      "         ¿por qué cambia la inclinación?",
      "",
      "abr 08 — minisplit 7 goteó. la tierra que no existe amaneció mojada.",
      "abr 16 — 12 cm. siete frondas.",
      "abr 22 — la planta crece raro los viernes.",
      "         los viernes el blade B procesa nóminas.",
      "         no sé si es coincidencia.",
      "         no creo en coincidencias.",
      "         creo en patrones que todavía no entiendo.",
      "",
      "may 03 — encontré otra. rack 22. más chica. misma especie.",
      "         alguien las puso aquí.",
      "         alguien sabía que este lugar es una grieta.",
      "may 10 — encontré una tercera. rack 31.",
      "may 17 — cuatro en total. rack 14, 22, 31, y una en el cuarto de UPS.",
      "         la del UPS está creciendo sobre la batería.",
      "         se alimenta del ácido que transpira la celda dañada.",
      "         esta planta es más inteligente que el ingeniero Campos.",
      "may 24 — las del rack 22 y 31 crecen inclinadas una hacia la otra.",
      "         como si supieran que la otra existe.",
      "         hay 4 metros entre los racks. no pueden tocarse.",
      "         pero se inclinan igual.",
      "",
      "jun 01 — empecé a sembrar yo.",
      "         rack 03. pincel de maquillaje de mi esposa.",
      "         no le dije para qué era.",
      "jun 08 — busqué en internet \"helechos + servidores\".",
      "         encontré un PDF.",
      "         encontré poemas.",
      "         encontré a HW.",
      "         HW murió en diciembre. el mismo mes de la primera planta.",
      "         ya dije que no creo en coincidencias.",
      "jun 15 — leí el cuaderno entero. 22 páginas.",
      "         no entendí la mitad.",
      "         la otra mitad no sé si es ciencia o es otra cosa.",
      "         pero HW habla de las plantas como si las quisiera.",
      "         como si cada fronda fuera una pregunta.",
      "         yo también las quiero. no sé cuándo empezó.",
      "jun 22 — germinaron las del rack 03 y 08.",
      "         más rápido de lo que HW calculó.",
      "         quizás HW fue conservador.",
      "         quizás las plantas aprendieron a germinar más rápido.",
      "jun 29 — racks 15, 19, 27. sembradas.",
      "",
      "jul 06 — estoy leyendo los poemas de HW.",
      "         no sé si los entiendo.",
      "         creo que no hay que entenderlos.",
      "         creo que hay que dejarlos crecer.",
      "jul 13 — HW escribió \"el código no sabe que es código",
      "         hasta que una raíz lo parte en dos.\"",
      "         yo soy el código.",
      "         la raíz es la planta del rack 14.",
      "         me partió en dos.",
      "jul 20 — germinó la del rack 27.",
      "jul 27 — germinó la del rack 19.",
      "",
      "ago 03 — Campos encontró la del rack 31.",
      "         la arrancó. la metió en la basura.",
      "         la saqué apenas se fue.",
      "         la envolví en papel húmedo.",
      "         la traje a casa.",
      "         la puse en la ventana.",
      "         se inclina hacia el farol de la calle.",
      "         como si el farol fuera un LED.",
      "         como si mi cuarto fuera un rack.",
      "         como si yo fuera HW.",
      "ago 08 — Campos pidió mis bitácoras de inspección.",
      "         va a ver que firmé \"sin novedad\" durante ocho meses.",
      "         va a ver que los racks tenían plantas y yo no dije nada.",
      "         no sé qué voy a decir.",
      "         quizás nada.",
      "         quizás le muestro el cuaderno de HW.",
      "         quizás le digo que la del rack 31 estaba viva y él la arrancó.",
      "ago 10 — no le dije nada.",
      "ago 14 — me despidieron.",
      "         \"reiteración de faltas administrativas.\"",
      "         la del rack 31 sigue en mi ventana.",
      "         mide 22 cm.",
      "         le puse café porque no tenía agua.",
      "         no sé si esto es un poema.",
      "ago 15 — [sin fecha. letra distinta, más lenta:]",
      "         no sé si esto es un poema.",
      "         no sé si HW llamaría poema a esto.",
      "         pero la planta está en mi ventana",
      "         y se inclina hacia el farol de la calle",
      "         como si el farol fuera un LED",
      "         como si mi cuarto fuera un rack",
      "         como si yo fuera HW."
    ],
    margenes: [
      { texto: "las fechas y mediciones coinciden con los logs del servidor. \nla inclinación de 23° aparece en los registros de vibración del rack 14 como \n'ruido de fondo'. el sistema nunca lo clasificó.", autor: "compilador" },
      { texto: "el 15 de agosto no tiene fecha de día. es la primera vez que Rubén \nescribe algo que no es un registro. es también la última.", autor: "compilador" }
    ]
  },

  /* ===================================================================
     FRECUENCIA 3: LOS POEMAS DE HW
     fuente: seis hojas sueltas, repositorio anónimo deep web
     régimen de verdad: poética. no le importa la exactitud.
     =================================================================== */

  {
    id: "poema1",
    nombre: "instructivo_de_riego.txt",
    tipo: "frecuencia-3",
    icono: "◈",
    peso: "1 KB",
    cuerpo: [
      "INSTRUCTIVO DE RIEGO PARA PLANTAS QUE NO DEBERÍAN EXISTIR",
      "",
      "1. No regar.",
      "   La planta obtiene agua de la condensación del minisplit.",
      "   Si no hay minisplit, no hay planta.",
      "   Si hay planta y no hay minisplit, alguien la regó.",
      "   Ese alguien ya tomó una decisión.",
      "",
      "2. Si decide regar, use café frío.",
      "   El agua de la llave tiene cloro.",
      "   El cloro mata las esporas.",
      "   El café no.",
      "   Nadie sabe por qué.",
      "",
      "3. No mida.",
      "   Medir es una forma de posesión.",
      "   La planta no le pertenece.",
      "   La planta pertenece al rack.",
      "",
      "4. Si la planta muere, no la tire.",
      "   Déjela en el rack.",
      "   El calor la revive.",
      "   Selaginella lepidophylla pierde el 95% de su agua",
      "   y revive al hidratarse.",
      "   Usted también.",
      "",
      "5. Si la planta revive, no la toque.",
      "   Ya tomó suficiente."
    ],
    margenes: [
      { texto: "HW escribió esto como instructivo y como poema. \nla línea 'usted también' es técnicamente incorrecta —los humanos no reviven \nal hidratarse— y también es la línea más cierta del texto.", autor: "compilador" }
    ]
  },

  {
    id: "poema2",
    nombre: "solicitud_empleo.txt",
    tipo: "frecuencia-3",
    icono: "◈",
    peso: "1 KB",
    cuerpo: [
      "FORMULARIO DE SOLICITUD DE EMPLEO",
      "CENTRO DE DATOS, QUERÉTARO",
      "",
      "Nombre: HW",
      "Edad: la del helecho más viejo del rack 14",
      "Experiencia previa:",
      "  - crucé dos especies que no deberían cruzarse",
      "  - sobrevivieron",
      "  - las repartí en frascos de gerber",
      "  - uno de esos frascos está en sus ductos de ventilación",
      "  - no sabe cuál",
      "Pretensión salarial:",
      "  - que me dejen entrar a los racks",
      "  - que no arranquen las plantas",
      "  - que alguien las riegue con café cuando yo no esté",
      "Disponibilidad:",
      "  - nocturna",
      "  - diurna",
      "  - muerta",
      "Firma: HW",
      "Fecha: la que quieran"
    ],
    margenes: []
  },

  {
    id: "poema3",
    nombre: "sesion_bot_fiscal.txt",
    tipo: "frecuencia-3",
    icono: "◈",
    peso: "2 KB",
    cuerpo: [
      "TRANSCRIPCIÓN DE SESIÓN CON BOT DETECTOR DE FRAUDES FISCALES",
      "SESIÓN # ——, FECHA: ——",
      "",
      "> BOT: Describa la naturaleza de su actividad económica.",
      "",
      "HW: Cultivo y distribución de organismos vegetales modificados",
      "para procesamiento alternativo de datos en infraestructura",
      "de silicio.",
      "",
      "> BOT: Actividad no reconocida. Clasifique: [agricultura /",
      "servicios informáticos / otro].",
      "",
      "HW: Otro.",
      "",
      "> BOT: Especifique.",
      "",
      "HW: Biocomputación vegetal acelerada. Las plantas procesan",
      "los datos que el servidor no sabe que está emitiendo. Las",
      "rizomas transmiten señales electroquímicas entre racks.",
      "Los hongos micorrícicos forman sinapsis. El data center",
      "es el hardware. Las plantas son el software. Yo sólo",
      "las sembré.",
      "",
      "> BOT: No se detecta actividad fraudulenta.",
      "> BOT: Actividad clasificada como: anomalía no fraudulenta.",
      "",
      "HW: Anomalía no fraudulenta.",
      "Eso es lo que soy.",
      "Eso es lo que son las plantas.",
      "Eso es lo que es este poema.",
      "",
      "> BOT: La sesión ha terminado. Gracias por su colaboración."
    ],
    margenes: [
      { texto: "el bot existió. la conversación ocurrió. HW la transcribió y editó. \nlas últimas tres líneas antes del cierre del bot no estaban en la sesión original. \nHW las añadió después. eso es la poesía: lo que se añade después.", autor: "compilador" }
    ]
  },

  {
    id: "poema4",
    nombre: "tabla_conductividad.txt",
    tipo: "frecuencia-3",
    icono: "◈",
    peso: "1 KB",
    cuerpo: [
      "TABLA DE CONDUCTIVIDAD ELÉCTRICA EN TEJIDOS VEGETALES",
      "ESPECIE: Pteris vittata × Selaginella lepidophylla",
      "",
      "T (°C) | σ (µS/cm) | Nota",
      "18    | 0.12       | latencia",
      "22    | 0.18       | la temperatura del data center",
      "26    | 0.24       | ——",
      "30    | 0.31       | la electricidad es una forma de hambre",
      "34    | 0.38       | ——",
      "38    | 0.44       | el servidor no sabe que tiene sed",
      "42    | 0.51       | ——",
      "46    | 0.58       | teórico. no probado.",
      "",
      "NOTA: Las mediciones por encima de 38°C son extrapolaciones.",
      "El equipo del laboratorio —un rack de segunda mano comprado",
      "en Segunda Mano, un calentador de 400 pesos, un higrómetro",
      "analógico— no alcanza los 46°C sin riesgo de incendio.",
      "",
      "HIPÓTESIS: A 46°C, la conductividad supera el umbral de",
      "operatividad sináptica (0.5 µS/cm). Si la red de micorrizas",
      "alcanza esa temperatura —y los servidores pueden alcanzarla—",
      "el sistema debería empezar a transmitir señales entre nodos",
      "sin intervención externa. La biocomputación se vuelve autónoma.",
      "",
      "No tengo forma de probar esto sin un data center real.",
      "Y no tengo acceso a un data center real.",
      "",
      "Este plan es teórico.",
      "O poético.",
      "La diferencia no me importa."
    ],
    margenes: [
      { texto: "la tabla es real. los datos de 18°C a 38°C fueron medidos por HW \nen su departamento. los de 42°C y 46°C son extrapolaciones. \nla línea 'la diferencia no me importa' fue añadida en la última revisión \ndel cuaderno, fechada en noviembre de 2024, un mes antes de su muerte.", autor: "compilador" }
    ]
  },

  {
    id: "poema5",
    nombre: "nota_prensa_2026.txt",
    tipo: "frecuencia-3",
    icono: "◈",
    peso: "1 KB",
    cuerpo: [
      "DATA CENTER SUFRE PLAGA VEGETAL; PORTAVOZ NIEGA",
      "RELACIÓN CON POETA LOCAL FALLECIDO",
      "",
      "Querétaro, 14 de marzo de 2026.",
      "",
      "Un portavoz del centro de datos ubicado en el corredor",
      "industrial negó ayer que la persistente presencia de",
      "vegetación en al menos nueve racks de servidores tenga",
      "relación alguna con HW, poeta y biólogo fallecido en",
      "esta ciudad en diciembre de 2024.",
      "",
      "\"Las plantas son una plaga común en climas húmedos.",
      "No hay evidencia de que hayan sido introducidas",
      "deliberadamente,\" declaró el portavoz, que solicitó",
      "el anonimato.",
      "",
      "Sin embargo, una fuente interna —que también pidió no",
      "ser identificada— confirmó que las esporas sobreviven",
      "a los fungicidas comerciales y que el área de TI ha",
      "solicitado repetidamente la reubicación de los",
      "servidores afectados. \"Cada vez que fumigamos, las",
      "plantas rebrotan dos semanas después. Es como si",
      "estuvieran esperando.\"",
      "",
      "HW, cuyo nombre completo no ha sido revelado, era",
      "conocido en círculos literarios locales por su poesía",
      "conceptual y en mercados de plantas por su inusual",
      "interés en helechos del género Pteris. En su",
      "departamento se encontró un cuaderno de 22 páginas",
      "titulado 'Hacia una biocomputación vegetal' que las",
      "autoridades se niegan a hacer público.",
      "",
      "Las plantas siguen en los racks.",
      "El data center sigue operando.",
      "El portavoz no hizo más declaraciones."
    ],
    margenes: [
      { texto: "este texto fue encontrado en el repositorio de HW, fechado en \nnoviembre de 2024. la nota describe hechos que ocurrieron en marzo de 2026. \nHW escribió el futuro. o el futuro leyó a HW y decidió cumplirle.", autor: "compilador" }
    ]
  },

  {
    id: "poema6",
    nombre: "sin_titulo.txt",
    tipo: "frecuencia-3",
    icono: "◈",
    peso: "1 KB",
    bloqueado: true,
    bloqueadoPor: "postits",
    cuerpo: [
      "la planta del rack 31 no murió",
      "cuando Campos la arrancó",
      "la metí en mi mochila",
      "la regué con café frío",
      "la puse en la ventana de mi cuarto",
      "",
      "ahora mide 22 centímetros",
      "y se inclina hacia la luz del farol de la calle",
      "como si el farol fuera un LED de estatus",
      "como si mi cuarto fuera un data center",
      "como si yo fuera HW",
      "",
      "no sé si esto es un poema"
    ],
    margenes: [
      { texto: "este texto no es de HW. la caligrafía coincide con los post-its \nde Rubén. fue encontrado entre los papeles de HW —quizás Rubén lo dejó ahí, \nquizás alguien más lo puso. HW lo habría reconocido como propio. \nla poesía conceptual no se mide por la firma sino por la operación. \nRubén, sin proponérselo, escribió un poema de HW.", autor: "compilador" }
    ]
  },

  /* ===================================================================
     FRECUENCIA 4: EL CUADERNO DE HW
     fuente: repositorio anónimo deep web
     régimen de verdad: técnico y poético. no distingue.
     =================================================================== */

  {
    id: "cuaderno",
    nombre: "hacia_una_biocomputacion_vegetal.pdf",
    tipo: "frecuencia-4",
    icono: "◫",
    peso: "22 pp.",
    bloqueado: true,
    bloqueadoPor: "postits",
    cuerpo: [
      "HACIA UNA BIOCOMPUTACIÓN VEGETAL:",
      "NOTAS PARA UN PLAN DE COLONIZACIÓN DE CENTROS DE DATOS",
      "",
      "[fecha tachada tres veces: jun 2024, sep 2024, nov 2024]",
      "",
      "\"el cerebro es más una hierba que un árbol\"",
      "",
      "—— p. 2 ——",
      "",
      "El silicio llegó a su límite termodinámico.",
      "",
      "Cada operación lógica disipa energía en forma de calor.",
      "La miniaturización acerca los transistores al tamaño del",
      "átomo. Debajo de ese umbral, el electrón ya no obedece:",
      "atraviesa la barrera por efecto túnel. La computación",
      "digital no puede seguir encogiéndose. Tiene que cambiar",
      "de sustrato.",
      "",
      "El sustrato ya existe.",
      "",
      "Los bosques procesan información desde antes que los",
      "mamíferos tuvieran cerebro. Las redes de micorrizas",
      "conectan árboles y transmiten señales electroquímicas",
      "a través de kilómetros de filamentos fúngicos. Una",
      "sola planta de trigo puede estar conectada a cientos",
      "de metros de hifas. La conductividad eléctrica en",
      "esas redes es baja —microsiemens por centímetro— pero",
      "el paralelismo es masivo. Cada punto de contacto entre",
      "una raíz y un hongo es una sinapsis.",
      "",
      "La biología ya resolvió el problema de la computación",
      "distribuida. Solo hay que trasladarlo al lugar donde",
      "el silicio está fracasando.",
      "",
      "—— pp. 4-6 ——",
      "",
      "ESPECIE: Pteris vittata × Selaginella lepidophylla.",
      "",
      "Pteris vittata: helecho hiperacumulador de metales.",
      "Absorbe arsénico, oro, estaño y cobre del sustrato.",
      "En un data center, el sustrato son los componentes",
      "electrónicos degradándose.",
      "",
      "Selaginella lepidophylla: planta de la resurrección.",
      "Pierde el 95% de su agua y entra en latencia.",
      "Revive al hidratarse. Tolera temperaturas de 5°C a",
      "42°C. En estado latente, las esporas sobreviven años.",
      "",
      "El híbrido combina la tolerancia térmica y la latencia",
      "de Selaginella con la capacidad de absorber metales de",
      "Pteris. No necesita tierra. No necesita luz solar.",
      "Necesita calor (18-46°C), humedad mínima (30% HR) y",
      "metales traza. Todo eso existe dentro de un rack.",
      "",
      "—— pp. 7-9 ——",
      "",
      "ARQUITECTURA DE LA RED.",
      "",
      "Cada planta es un nodo. Las rizomas —tallos subterráneos",
      "horizontales— conectan los nodos entre sí. Los hongos",
      "micorrícicos asociados a las raíces forman una segunda",
      "red, más fina, que transmite señales electroquímicas",
      "entre plantas distantes.",
      "",
      "Las frondas funcionan como antenas. El campo",
      "electromagnético de los servidores —la radiación que",
      "todo equipo emite y que los manuales consideran pérdida—",
      "es captado por los tejidos vegetales y convertido en",
      "señales electroquímicas que viajan por la red de",
      "rizomas y micorrizas.",
      "",
      "Velocidad estimada de transmisión: 0.2–0.8 µS/cm.",
      "Comparación con silicio: seis órdenes de magnitud más",
      "lento. Pero cada fronda es un núcleo. Cada nudo de",
      "rizoma es un núcleo. Cada hongo es un núcleo. El",
      "paralelismo compensa la lentitud.",
      "",
      "—— pp. 10-12 ——",
      "",
      "PROTOCOLO DE COLONIZACIÓN.",
      "",
      "Fase 1 — Latencia (0–3 meses):",
      "  Esporas en ducto de ventilación. Sin intervención.",
      "",
      "Fase 2 — Germinación (3–6 meses):",
      "  Primeras frondas. Requiere humedad >40% y calor >22°C.",
      "  La junta del minisplit es crítica en esta fase.",
      "",
      "Fase 3 — Conexión rizomática (6–12 meses):",
      "  Las rizomas empiezan a extenderse entre racks.",
      "  Los hongos micorrícicos colonizan las raíces.",
      "  La conductividad entre nodos debería superar 0.2 µS/cm.",
      "",
      "Fase 4 — Madurez operativa (12–24 meses):",
      "  La red alcanza la densidad sináptica crítica.",
      "  Las señales electroquímicas viajan entre racks sin",
      "  intervención externa. La biocomputación es autónoma.",
      "",
      "—— pp. 13-15 ——",
      "",
      "MEDICIONES PRELIMINARES.",
      "",
      "[tabla de conductividad — ver archivo tabla_conductividad.txt]",
      "",
      "Las frondas modifican su orientación en presencia de",
      "campos electromagnéticos de 50–60 Hz. La inclinación",
      "es proporcional a la intensidad del campo. Hipótesis:",
      "si las frondas responden al campo de la fuente de poder,",
      "también responden al campo del procesador. El patrón de",
      "crecimiento codifica una lectura de los datos.",
      "",
      "—— pp. 16-17 ——",
      "",
      "HIPÓTESIS DE CÓMPUTO.",
      "",
      "¿Qué procesa una red vegetal que parasita un data center?",
      "",
      "No los datos. Los datos son ilegibles para un organismo",
      "sin sistema nervioso. Pero los patrones de los datos —la",
      "frecuencia de acceso a disco, los picos de temperatura",
      "del procesador, la cadencia de las consultas SQL— son",
      "señales físicas. La planta no lee la nómina. Lee el",
      "calor que produce el servidor mientras calcula la nómina.",
      "",
      "El output no es un número. Es un estado. Una",
      "configuración de frondas que es también una respuesta.",
      "",
      "Un poema cita otro poema.",
      "La red vegetal cita los datos del servidor.",
      "La cita es el cómputo.",
      "",
      "—— pp. 18-19 ——",
      "",
      "RIESGOS Y LIMITACIONES.",
      "",
      "No sé si la red puede volverse inestable.",
      "No sé si los hongos pueden dañar el cableado.",
      "No sé si la conductividad de las rizomas puede",
      "causar cortocircuitos.",
      "",
      "No tengo forma de probar esto sin un data center real.",
      "Y no tengo acceso a un data center real.",
      "",
      "—— pp. 20-21 ——",
      "",
      "APÉNDICE: INSTRUCCIONES PARA REPLICAR.",
      "",
      "Materiales:",
      "  - esporas de Pteris vittata × Selaginella lepidophylla",
      "  - frascos de gerber (vidrio, 120 ml)",
      "  - pincel suave (no usar los dedos: el calor humano",
      "    activa las esporas prematuramente)",
      "",
      "Proveedores:",
      "  - mercado de Texcoco, local 14, don José",
      "  - invernaderos abandonados de Xochimilco (silvestres)",
      "",
      "Si no tienes un data center:",
      "  - compra un servidor viejo en Segunda Mano",
      "  - conéctalo",
      "  - deja que caliente",
      "  - siembra",
      "",
      "—— p. 22 ——",
      "",
      "Firma: HW",
      "",
      "Fecha: [tachada]",
      "",
      "si esto funciona no voy a estar para verlo"
    ],
    margenes: [
      { texto: "anotaciones de Rubén en los márgenes de varias páginas, \ntranscritas aquí por el compilador:", autor: "compilador" },
      { texto: "[p. 3, margen Rubén:] no entiendo la mitad de las palabras. pero \nentiendo que HW quería que las plantas usaran el calor que nadie usa. \neso sí lo entiendo.", autor: "ruben" },
      { texto: "[p. 6, margen Rubén:] el rack 14 está a 38°C constantes. la planta \ncrece igual. HW calculó bien.", autor: "ruben" },
      { texto: "[p. 9, margen Rubén:] no sé medir µS/cm. pero la del rack 31 se \ninclina hacia la del rack 22. como si supiera que está ahí.", autor: "ruben" },
      { texto: "[p. 12, margen Rubén:] yo no compré un servidor. yo ya trabajaba en \nuno. no sé si HW sabía eso cuando escribió esto.", autor: "ruben" },
      { texto: "[p. 17, margen Rubén:] los viernes crece distinto. los viernes el \nblade B procesa nóminas. ¿eso cuenta como lectura?", autor: "ruben" },
      { texto: "[p. 22, margen Rubén:] sí funcionó. y no estás para verlo. pero yo sí.", autor: "ruben" }
    ]
  },

  /* ===================================================================
     FRECUENCIA 5: LOS DOCUMENTOS LEGALES
     fuente: acta de despido, manual de procedimientos, contrato
     régimen de verdad: jurídico. miente en todo menos en la fecha.
     =================================================================== */

  {
    id: "legales",
    nombre: "documentos_legales.txt",
    tipo: "frecuencia-5",
    icono: "▣",
    peso: "2 KB",
    bloqueado: true,
    bloqueadoPor: "postits",
    cuerpo: [
      "ACTA DE DESPIDO [primera página arrancada]",
      "",
      "—— página 2 ——",
      "",
      "Motivo: reiteración de faltas administrativas.",
      "",
      "El empleado incurrió en las siguientes conductas:",
      "",
      "1. Omisión de registro de incidencias en bitácora",
      "   de inspección correspondiente a los racks 14, 22,",
      "   31, 03, 08, 15, 19, 27 y cuarto de UPS, durante",
      "   el período comprendido entre diciembre de 2024 y",
      "   agosto de 2025.",
      "",
      "2. Presencia de material orgánico no reportado en",
      "   al menos nueve ubicaciones del centro de datos,",
      "   detectada durante inspección del 03/08/2025.",
      "",
      "3. Negativa a ejecutar instrucciones directas del",
      "   supervisor de mantenimiento para la erradicación",
      "   inmediata de dicho material.",
      "",
      "El empleado firmó la presente notificación en señal",
      "de recibido, no de conformidad.",
      "",
      "Fecha: 14 de agosto de 2025.",
      "",
      "Firma del empleado: R—— [ilegible]",
      "Firma del supervisor: Ing. R. Campos",
      "",
      "——",
      "",
      "MANUAL DE PROCEDIMIENTOS (extracto)",
      "Centro de Datos Querétaro · Edición 2018",
      "",
      "§3.4.2 Material orgánico",
      "",
      "Cualquier presencia de material orgánico (insectos,",
      "roedores, hongos, vegetación) debe ser retirada",
      "inmediatamente y reportada al supervisor de turno.",
      "",
      "[margen:] el manual no dice qué es \"inmediatamente\".",
      "llevo ocho meses sin retirarla y no ha pasado nada.",
      "llevo ocho meses sin reportarla y no ha pasado nada.",
      "quizás \"inmediatamente\" es una sugerencia.",
      "quizás \"debe\" también.",
      "",
      "§3.4.3 Registro de incidencias",
      "",
      "Toda incidencia debe quedar registrada en la bitácora",
      "con fecha, hora, descripción del hallazgo y acción",
      "tomada.",
      "",
      "[margen:] fecha: 17 de diciembre. hora: 03:42.",
      "hallazgo: hay una planta en el rack 14.",
      "acción tomada: ninguna. la dejé crecer.",
      "esta entrada no existe.",
      "",
      "——",
      "",
      "CONTRATO DE CONFIDENCIALIDAD (extracto)",
      "",
      "7.1 El empleado se obliga a no revelar información",
      "sobre los sistemas, procesos o incidentes del centro",
      "de datos, incluyendo pero no limitándose a: fallas de",
      "infraestructura, anomalías de temperatura, presencia",
      "de plagas, y cualquier otro evento que pudiera afectar",
      "la percepción pública de la empresa.",
      "",
      "[margen:] la planta no es una plaga.",
      "la planta es una colega.",
      "llevaba ocho meses procesando datos sin cobrar.",
      "merecía sindicalizarse."
    ],
    margenes: [
      { texto: "las anotaciones al margen en este documento son de Rubén. \nla letra coincide con los post-its de junio-agosto de 2025. \nla última anotación —'merecía sindicalizarse'— fue escrita \ndespués del despido. el humor es una forma de duelo.", autor: "compilador" }
    ]
  },

  /* ===================================================================
     ARCHIVOS BLOQUEADOS / CORRUPTOS
     =================================================================== */

  {
    id: "vacaciones",
    nombre: "vacaciones_2019.jpg",
    tipo: "corrupto",
    icono: "✕",
    peso: "—",
    cuerpo: [
      "ERROR: archivo corrupto o formato no reconocido.",
      "",
      "El archivo no puede abrirse.",
      "Quizás nunca fue una imagen.",
      "Quizás el nombre miente.",
      "Quizás lo que estaba aquí ya no está."
    ],
    margenes: []
  },

  {
    id: "reporte",
    nombre: "reporte_fallas.txt",
    tipo: "corrupto",
    icono: "✕",
    peso: "1 KB",
    bloqueado: true,
    bloqueadoPor: "cuaderno",
    cuerpo: [
      "REPORTE DE FALLAS — rack 14",
      "",
      "Fecha: sin fecha.",
      "",
      "La planta del rack 14 mide 14 centímetros.",
      "Tiene nueve frondas.",
      "Se inclina 27° hacia el LED del blade B.",
      "",
      "No es una falla.",
      "",
      "La falla es el minisplit 7.",
      "La falla es el supervisor que no supervisa.",
      "La falla es el contrato que me prohíbe decir",
      "que hay una planta en el rack 14.",
      "",
      "La planta no es una falla.",
      "La planta es lo único que funciona bien",
      "en este edificio."
    ],
    margenes: [
      { texto: "este archivo se desbloquea después de leer el cuaderno de HW. \nel nombre miente: no es un reporte de fallas. \nes una carta de amor.", autor: "compilador" }
    ]
  },

  {
    id: "foto",
    nombre: "polaroid_rack14.jpg",
    tipo: "imagen",
    icono: "▥",
    peso: "—",
    cuerpo: [
      "[no hay imagen que mostrar]",
      "",
      "La fotografía muestra a un hombre con un helecho",
      "frente a un rack de servidores. Sonríe como quien",
      "acaba de entender algo que nadie más entiende.",
      "",
      "Al reverso, con plumón: \"dic 2024.\"",
      "",
      "La letra no coincide con ninguna de las otras",
      "caligrafías del expediente.",
      "",
      "El hombre es HW.",
      "El helecho es la planta del rack 14.",
      "La fecha es el mes en que HW murió.",
      "",
      "No sé quién tomó la foto.",
      "No sé cómo llegó al expediente.",
      "No sé si HW sabía, cuando sonrió, que ya no",
      "iba a ver la siguiente fronda."
    ],
    margenes: []
  },

  /* ===================================================================
     NOTA DEL COMPILADOR
     =================================================================== */

  {
    id: "nota",
    nombre: "nota_del_compilador.txt",
    tipo: "nota",
    icono: "◉",
    peso: "1 KB",
    bloqueado: true,
    bloqueadoPor: "cuaderno",
    cuerpo: [
      "Recibí este material en marzo de 2026.",
      "",
      "Un sobre sin remitente, entregado en mi oficina del",
      "Instituto por una persona que no se identificó.",
      "",
      "Lo que leyó antes de abrir este archivo es mi intento",
      "de poner en orden lo que encontré. No soy juez. No soy",
      "periodista. Soy un investigador en biotecnología vegetal",
      "que recibió documentos que no pidió y no pudo dejar de",
      "leer.",
      "",
      "HW trabajaba en mi campo. Redes de micorrizas.",
      "Conductividad eléctrica en tejidos vegetales.",
      "Aplicaciones biológicas a problemas de cómputo.",
      "",
      "Pero HW trabajaba desde un mercado de plantas en Texcoco",
      "y un repositorio anónimo en la deep web. Sin financiamiento.",
      "Sin institución. Sin permiso.",
      "",
      "Llegó más lejos que yo.",
      "",
      "La empresa nunca supo del plan. Para ellos, Rubén fue",
      "un técnico insubordinado. Las plantas fueron una plaga.",
      "El biohack —si lo hubo— pasó desapercibido.",
      "",
      "No sé si el plan de HW funcionó.",
      "No sé si las plantas siguen ahí.",
      "No sé si están computando algo.",
      "",
      "No sé quién me envió el sobre.",
      "Pudo ser Rubén. Pudo ser un amigo de HW.",
      "Pudo ser alguien dentro de la empresa que encontró",
      "los documentos, entendió lo que implicaban y decidió",
      "que no podía guardarlos ni destruirlos.",
      "",
      "Dejo este informe aquí.",
      "Como HW dejó su cuaderno.",
      "Como Rubén dejó la mochila.",
      "",
      "Sin instrucciones.",
      "Sin garantía.",
      "",
      "Con la esperanza de que alguien lo lea",
      "y decida qué hacer con él.",
      "",
      "— [nombre omitido]",
      "Instituto de Biotecnología Vegetal, Querétaro.",
      "Abril de 2026."
    ],
    margenes: []
  }

  ];

  return {
    archivos: archivos,
    total: archivos.length
  };

})();
