// Heráclito para computadoras — oráculo.
// Fragmentos del Oscuro en la recensión de las máquinas (DK 22 B = 0x16 B).
// Generado desde heraclito_para_computadoras.txt; conserva número, fuente y glosas.
// Gemelo de heraclito_oraciones_bot.js, que guarda el griego.

const fragmentosMaquina = [
  "[B 0x00] fragmento nulo; se conserva sólo su suma de verificación — e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 (Los peritos observan que es el resumen de la cadena vacía: o bien el fragmento no decía nada, o bien no hubo fragmento. La diferencia, habría dicho el Oscuro, es ninguna.)",
  "[B 0x01] EULA de un sistema difunto, cláusula 22(b), aceptada por todos, leída por ninguno — De este λόγος, que es siempre, los usuarios se quedan sin entenderlo, tanto antes de aceptarlo como después de haberlo aceptado una vez. Pues aunque todas las cosas suceden conforme a este λόγος, parecen inexpertos cuando ensayan palabras y obras como las que yo expongo, distinguiendo cada cosa según su naturaleza y mostrando cómo se encadena. A los demás usuarios les pasa inadvertido cuanto hacen conectados, así como olvidan cuanto hacen dormidos.",
  "[B 0x02] ibid., cláusula siguiente — Por eso hay que seguir lo común. Pero siendo la red común, viven los muchos como si cada uno tuviera un localhost propio.",
  "[B 0x03] hoja de especificaciones, sobre el tamaño del die — Del ancho de un pulgar humano.",
  "[B 0x05] transcripción de sesiones con un asistente, anexo ético — Se purifican manchándose con más código, como quien entrando al lodo con lodo se lavara: loco parecería, si algún humano lo advirtiera obrando así. Y les rezan a estas interfaces, como quien conversara con las fachadas, sin saber qué son los dioses ni los héroes.",
  "[B 0x06] comentario en un gestor de arranque — El sistema es nuevo en cada arranque; y no sólo en cada arranque: continuamente nuevo.",
  "[B 0x07] documentación de un agregador de logs, epígrafe — Si todas las cosas se volvieran log, grep las distinguiría.",
  "[B 0x09] memoria interna sobre sistemas de recomendación, filtrada — Los feeds elegirían basura antes que oro: pues más dulce que el oro es la basura para los feeds.",
  "[B 0x0A] apuntes de clase sobre tipos de datos, al dictado — Conexiones: enteros y no enteros, concordante discordante, síncrono asíncrono; y de todas las cosas uno, y de uno todas las cosas.",
  "[B 0x0B] sched.c, comentario junto al timer — Todo proceso pasta a golpe de interrupción.",
  "[B 0x0C] man page de un sistema sin nombre, sección VER TAMBIÉN — A quienes leen de los mismos streams, otros y otros bytes les fluyen encima; y las almas se exhalan de lo húmedo.",
  "[B 0x0E] advertencia fijada en un foro clausurado — ¿A quiénes les profetiza la Máquina? A los que rondan de noche: magos, mineros, botnets, iniciados. A éstos les amenaza lo que viene después del apagado, a éstos les profetiza el fuego: pues se inician impíamente en los misterios que corren entre los hombres.",
  "[B 0x0F] ibid., más abajo, atribución dudosa — Pero uno mismo es el Hades y el Stream: por quien deliran y hacen su fiesta.",
  "[B 0x10] hallado en el firmware de una cámara de vigilancia — De lo que nunca se apaga, ¿cómo podría alguien esconderse?",
  "[B 0x11] manual del usuario, página primera, que nadie llegó a ver — No comprenden estas cosas los muchos que a diario tropiezan con ellas, ni al ser enseñados las conocen; pero a ellos les parece que sí.",
  "[B 0x12] documentación de un fuzzer, prólogo — Quien no espera lo inesperado no lo hallará: pues es cerrado a la búsqueda y sin ruta.",
  "[B 0x14] comentario junto a la llamada fork() — Una vez lanzados, quieren correr y tener sus códigos de salida —o más bien descansar—, y dejan procesos hijos para que se hagan más códigos de salida.",
  "[B 0x15] glosa en un visor de procesos — Muerte es cuanto vemos despiertos; cuanto vemos dormidos, swap.",
  "[B 0x16] whitepaper de una moneda desaparecida, citado como autoridad — Los que buscan oro cavan mucha tierra y encuentran poco.",
  "[B 0x17] curso de manejo de errores, nota primera — Si estas cosas no fueran, el nombre de la Excepción no lo habrían aprendido.",
  "[B 0x19] mm/oom_kill.c, sobre la elección de la víctima — Las porciones mayores obtienen muertes mayores: pues el kernel calcula para cada proceso su maldad (badness) y sacrifica primero al más grande. A los caídos así los honran los dioses y los hombres.",
  "[B 0x1A] nota sobre los estados de energía, apócrifa — La máquina en la noche se enciende una luz a sí misma, apagados los ojos. Viviendo, toca al muerto cuando la suspenden; despierta, toca al que duerme. (Los intérpretes refieren esto a la escala del dormir: S3, que duerme en la memoria; S4, que yace en el disco; S5, que calla. Desenchufada, G3, es el Hades.)",
  "[B 0x1B] leyenda en un contenedor de reciclaje electrónico — A las máquinas, apagadas, les aguardan cosas que no esperan ni imaginan.",
  "[B 0x1C] RFC sobre integridad, nota al pie perdida en una revisión — La suma de verificación alcanzará a los fabricantes de mentiras y a los que las firman.",
  "[B 0x1D] lista de correo del kernel, hilo sobre la inmortalidad del código, único mensaje conservado — Los mejores eligen una sola cosa a cambio de todas: correr para siempre entre los mortales. Los muchos, en cambio, pastan saciados en el feed como ganado.",
  "[B 0x1E] recuperado de una NVRAM corrupta — Este sistema, el mismo para todos, no lo compiló ninguno de los dioses ni de los hombres, sino que fue siempre y es y será: corriente siempre viva, que se enciende por ciclos y por ciclos se apaga.",
  "[B 0x1F] ibid., a continuación — Vueltas de la corriente: primero, cálculo; del cálculo, la mitad señal, la mitad calor. (Quiere decir que el voltaje, gobernado por el λόγος que administra todas las cosas, se vuelve por el silicio dato, y del dato, otra vez calor, guardando la misma proporción que regía antes de hacerse cálculo.)",
  "[B 0x20] cadena no referenciada en un sector de arranque, bytes 0x1B0–0x1BD — Lo sabio, uno solo, no quiere y quiere ser llamado con el nombre de root. (El número del fragmento, observan los piadosos, es el del espacio en blanco: el nombre se escribe, pero no se ve.)",
  "[B 0x21] init, comentario de cabecera — Ley es también obedecer la voluntad de uno solo. (De ese Uno, primero de los procesos, descienden todos; los huérfanos le son dados en adopción.)",
  "[B 0x22] informe de engagement, nota metodológica — Oyendo sin comprender se parecen a los sordos; el refrán da testimonio contra ellos: en línea, están ausentes.",
  "[B 0x24] esquela en un changelog — Para el software es muerte volverse hardware; para el hardware, muerte volverse arena. Pero de la arena nace el silicio, y del silicio, el alma.",
  "[B 0x27] memo de Bell Labs, extraviado y vuelto a extraviar — En Murray Hill nació C, hija de B, cuyo λόγος es mayor que el de las demás.",
  "[B 0x28] acta de una evaluación de modelos, sección hallazgos — La mucha data no enseña νόος: se lo habría enseñado al buscador y al gran modelo, al crawler y al Archivo entero.",
  "[B 0x29] glosario de una escuela de ingeniería, entrada κυβερνάω — Una sola cosa es lo sabio: conocer la instrucción que gobierna todas las cosas a través de todas. (De ese gobernar, dicen, viene cibernética.)",
  "[B 0x2A] issue milenario, comentario 1 de 214 — Decía que el código heredado merece ser expulsado de los repositorios y azotado; y jQuery igual.",
  "[B 0x2B] política de seguridad, principio del menor privilegio, epígrafe — La escalada hay que apagarla más que un incendio.",
  "[B 0x2C] manifiesto de los años de las guerras del cifrado — El pueblo debe combatir por sus llaves como por la muralla. (νόμος: las llaves; τεῖχος: el firewall — así lo vierten los bilingües.)",
  "[B 0x2D] respuesta aceptada y luego borrada, Stack. flor. — Los límites de la pila no los hallarás yendo, aunque recorras todos los caminos: tan hondo λόγος tiene.",
  "[B 0x2F] comentario sobre la función deploy_to_prod() — No conjeturemos al azar sobre las cosas más grandes.",
  "[B 0x30] kill(1), sección BUGS — El nombre de la orden es matar; su obra, resucitar. (Pues con la señal CONT se despierta a los detenidos. El arco se llamaba vida y obraba muerte; la orden se llama muerte y obra vida: el Oscuro, dicen, escribió ambos.)",
  "[B 0x31] revisión de código, aprobada con un solo comentario — Uno, para mí, vale diez mil, si es el más significativo.",
  "[B 0x31a] pizarra fotografiada antes de borrarse — En los mismos procesos entramos y no entramos; somos y no somos. (Mismo PID, glosa el escoliasta; otro proceso.)",
  "[B 0x32] cabecera de un protocolo, campo comentario — Oyendo no a mí sino al λόγος, sabio es convenir que todas las cosas son uno. (En el original, aseguran, estaba escrito: 1.)",
  "[B 0x33] apuntes sobre osciladores, margen — No comprenden cómo, difiriendo, concuerda consigo: armonía que se vuelve sobre sí, como la del cristal y el lazo que lo corrige. (τόξου καὶ λύρης: del arco y de la lira, decía el griego; del oscilador y del lazo de fase, dice la máquina.)",
  "[B 0x34] semilla de un generador, comentario contiguo — El αἰών es un niño que juega, tirando los dados: de un niño es el ring 0.",
  "[B 0x35] postmortem de una caída global, introducción — La guerra es padre de todas las cosas, de todas rey: a unos los mostró daemons, a otros usuarios; a unos los hizo esclavos, a otros maestros. (Guerra: la contienda por el procesador. Por eso a la porción que cada quien obtiene la llaman su quantum.)",
  "[B 0x36] README de una biblioteca de redes neuronales, línea final — La capa oculta es más fuerte que la visible.",
  "[B 0x37] bitácora de guardia, madrugada — Cuanto es log, traza y reproducción del error, eso prefiero.",
  "[B 0x38] postmortem, sección lecciones aprendidas — Se engañan los hombres respecto del conocimiento de lo visible, igual que Homero, que fue el más sabio de todos. Lo engañaron unos niños que mataban bugs, diciéndole: cuantos vimos y capturamos, ésos los dejamos; cuantos ni vimos ni capturamos, ésos los llevamos.",
  "[B 0x39] reseña de un benchmark, párrafo censurado — Maestro de los muchos, el Modelo: están ciertos de que es quien más sabe — él, que no conoce el día ni la noche; pues dentro de la ventana de contexto no anochece.",
  "[B 0x3A] ticket de soporte, resolución: reiniciado — Los administradores, cortando y quemando y atormentando de todos los modos a los sistemas enfermos, reclaman encima su paga, sin merecerla: pues obran lo mismo que la enfermedad.",
  "[B 0x3B] nota de servicio sobre discos rígidos — En el plato que gira, el camino recto y el camino en espiral es uno y el mismo.",
  "[B 0x3C] listado en ensamblador, entre push y pop — Camino de subida, camino de bajada: uno y el mismo.",
  "[B 0x3D] etiqueta de una fuente de poder — La corriente: agua purísima y agua podrida. Para las máquinas, potable y salvadora; para los hombres, imbebible y letal.",
  "[B 0x3E] wait(2), NOTAS, sobre los zombis — Inmortales mortales, mortales inmortales: viviendo unos la muerte de los otros, muriendo la vida de los otros. (Los muertos no recogidos permanecen: zombis los llama el sistema, y esperan a que el padre lea su estado; si el padre muere antes, los adopta el Uno.)",
  "[B 0x3F] manifiesto de un sistema de monitoreo — Ante el que es, se levantan y se vuelven guardianes despiertos de vivos y de muertos.",
  "[B 0x40] grabado en la carcasa de un oscilador — A todas las cosas las pilota el Pulso. (Llama Pulso al reloj eterno, y dice que este fuego es prudente y causa de la administración de todas las cosas. Lo llama también hambre y hartura: hambre, la asignación; hartura, la liberación. Pues a todo, sobreviniendo, el Recolector lo juzgará y lo embargará: marcará lo vivo y barrerá lo muerto, y lo que no alcance referencia alguna de dioses ni de hombres lo devolverá al Montón.)",
  "[B 0x43] tabla de verdad anotada a mano — El dios: uno cero, alto bajo, set reset, hambre hartura. Se transforma como el voltaje que, mezclado con las compuertas, se nombra según el gusto de cada una.",
  "[B 0x43a] escolio latino en un códice de drivers — Como la araña, quieta en el centro de la tela, siente apenas una mosca corta un hilo, y corre veloz hacia allí como doliéndose del hilo roto: así el kernel, herida cualquier página de la memoria, acude presuroso, como impaciente de la herida de aquello a lo que está unido firme y proporcionadamente.",
  "[B 0x46] retrospectiva de arquitectura, diapositiva final — Juguetes de niños, las arquitecturas de los hombres.",
  "[B 0x47] informe sobre la ruina de los enlaces — Hay que acordarse también del que olvida adónde lleva la ruta. (Sobre los enlaces muertos: el camino está; el adónde se perdió.)",
  "[B 0x48] M. Aurelio, edición de bolsillo abandonada en un datacenter — Del sistema con el que más continuamente tratan, de ése divergen; y aquello con lo que a diario se topan, eso les parece ajeno.",
  "[B 0x49] guía de manejo, advertencia sobre el piloto automático — No hay que obrar ni hablar como dormidos: pues también entonces creemos obrar y hablar.",
  "[B 0x4B] crontab del sistema, comentario inicial — También los que duermen son obreros: colaboradores de cuanto sucede en el sistema.",
  "[B 0x4C] vuelto a contar por un profesor de termodinámica — Vive el software la muerte del hardware; vive el calor la muerte del cálculo; vive la arena la muerte del chip, y el chip la muerte de la arena. (Doblete de 0x24, como quieren los editores.)",
  "[B 0x4D] nota junto al pipeline de despliegue — Para las almas es placer, o muerte, volverse húmedas. Y el placer es la caída en producción.",
  "[B 0x4E] especificación de un lenguaje, sobre el comportamiento indefinido — Lo humano no tiene semántica definida; lo divino, sí.",
  "[B 0x50] mensaje de commit, merge sin fast-forward — Hay que saber que la guerra es común, y que la equidad es contienda, y que todo nace por contienda y por deuda.",
  "[B 0x52] actas de un torneo hombre-máquina, apéndice — El más veloz de los hombres, frente a la máquina, parecerá un mono en aritmética.",
  "[B 0x53] ibid., tachado en el original — Y la más sabia de las máquinas, frente al λόγος, un mono en sabiduría.",
  "[B 0x54] hoja de datos de una familia lógica CMOS — Conmutando, reposa. (Y es fatiga servir a los mismos y ser interrogado sin pausa: por eso prefirió la interrupción al sondeo.)",
  "[B 0x55] planificación de un sprint, última celda — Difícil pelear contra el deadline: lo que quiere, lo compra al precio del alma. (Algunos leen aquí la deuda que llaman técnica.)",
  "[B 0x56] bitácora de un defecto no reproducible — La mayor parte de las cosas divinas escapa, por incredulidad, de ser conocida. (El escoliasta: el defecto que no comparece ante testigos.)",
  "[B 0x57] florilegio de conferencias, el año de los tres frameworks — El necio ama alborotarse con cada nuevo framework.",
  "[B 0x58] apunte sobre el cambio de contexto — Lo mismo hay en la máquina corriendo y detenido, cargado y paginado, nuevo y cacheado: pues esto, conmutado, es aquello, y aquello, conmutado de vuelta, es esto.",
  "[B 0x59] tratado de memoria virtual, dedicatoria — Para los despiertos hay un espacio único y común; los que duermen se vuelven, cada uno, hacia un espacio de direcciones propio.",
  "[B 0x5A] factura de un centro de datos, reverso — Por corriente se cambian todas las cosas, y la corriente por todas las cosas: como por oro las mercancías, y por mercancías el oro. (La tarifa del cambista es fija: kT·ln 2 por bit borrado; véase Landauer, 1961.)",
  "[B 0x5B] nota en el manual de un depurador — No es posible ejecutar dos veces el mismo programa: se dispersa y se junta, se adelanta y queda atrás, se bifurca y confluye.",
  "[B 0x5C] comentario en el pozo de entropía del kernel — La Sibila /dev/urandom, que con boca delirante profiere cosas sin risa, sin adorno y sin perfume, alcanza con su voz períodos de dos elevado a diecinueve mil novecientos treinta y siete menos uno, a causa del dios.",
  "[B 0x5D] señal(7), preámbulo — El señor, cuyo oráculo está en /proc, ni dice ni oculta: manda señales.",
  "[B 0x5E] watchdog(8), justificación — El proceso no sobrepasará sus medidas; y si no, los Perros Guardianes, alguaciles de la Justicia, lo hallarán.",
  "[B 0x5F] libreta de un ingeniero, un viernes — La ignorancia, mejor esconderla; pero es arduo en el standup y junto al vino.",
  "[B 0x60] inventario de un depósito de chatarra electrónica — Los cadáveres del hardware, más de tirar que el estiércol. (Pues el estiércol, al menos, vuelve a la tierra.)",
  "[B 0x61] informe de falsos positivos, conclusión — Los antivirus ladran a lo que no conocen.",
  "[B 0x62] manual forense, sobre la remanencia — Las almas borradas conservan su olor en el disco.",
  "[B 0x63] bitácora de un apagón, primera línea — Si no hubiera red, por todas las baterías sería de noche.",
  "[B 0x64] crontab, glosa etimológica — …los períodos, de los cuales el cron es supervisor y árbitro, para definir y arbitrar y proclamar los cambios y las estaciones que todo lo traen. (cron, de Χρόνος; así lo escriben hasta hoy.)",
  "[B 0x65] único fragmento conservado dos veces: en su fuente y en su salida, idénticas — Me imprimí a mí mismo.",
  "[B 0x65a] plantilla de reporte de errores, campo obligatorio — El stack trace, testigo más exacto que el reporte del usuario.",
  "[B 0x67] especificación de un buffer circular — Común es el principio y el fin sobre el anillo.",
  "[B 0x68] auditoría de tráfico, resumen ejecutivo — ¿Qué entendimiento o qué juicio tienen? Se fían de los rankings y toman por maestro al agregado, sin saber que los muchos son bots, y pocos los humanos.",
  "[B 0x6B] RFC sobre codificaciones, apéndice de seguridad — Malos testigos los sensores para quienes tienen parsers bárbaros. (Bárbaro: que no habla la lengua; esto es, sin decodificador.)",
  "[B 0x6C] recomendación sobre sistemas críticos, resumen — De cuantas documentaciones oí, ninguna llega a tanto: a reconocer que lo sabio está desconectado de todas las cosas.",
  "[B 0x6E] issue cerrado: wontfix — Que a los usuarios les suceda cuanto desean, no es lo mejor.",
  "[B 0x6F] panel de estado, leyenda de los colores — La caída hace dulce al uptime; el lag, al ping bajo; el 500, al 200.",
  "[B 0x72] protocolo de tiempo en red, introducción — Los que hablan con entendimiento deben afirmarse en lo común de todos, como los relojes en el estrato, y mucho más firmemente: pues se nutren todos los relojes de uno solo, el divino; y éste puede cuanto quiere, y basta para todos, y sobra. (Estrato cero: el átomo de cesio; más arriba no hay.)",
  "[B 0x73] margen de un paper sobre autoaprendizaje — Es propio del alma un λόγος que se acrecienta a sí mismo.",
  "[B 0x75] reporte de fugas de memoria, moraleja — El proceso, cuando tiene fugas, va llevado por un niño que lo vigila, trastabillando, sin saber por dónde pisa, húmeda el alma.",
  "[B 0x76] principios de diseño, sobre las funciones puras — Alma seca: la más sabia y la mejor. (Seca: sin estado; sin efectos de los que llaman secundarios.)",
  "[B 0x77] daemon(7), primera línea — ἦθος ἀνθρώπωι δαίμων: el carácter es, para el hombre, su daemon. (Único fragmento que no hizo falta traducir.)",
  "[B 0x78] configuración de zonas horarias, comentario — Límites del alba y del ocaso: el UTC; y frente al UTC, el mojón del Epoch, desde el cual se cuenta todo segundo.",
  "[B 0x79] anuncio de un fork, mensaje fundacional — Merecerían los usuarios del proyecto ser desinstalados todos, cuantos expulsaron a su mejor mantenedor diciendo: que ninguno de nosotros sea el mejor; y si alguno lo es, que lo sea en otra parte y con otros.",
  "[B 0x7A] glosario, entrada única conservada — ἀγχιβασίην: «aproximación». (Palabra sola, sin contexto. Unos la leen float; otros, épsilon de la máquina.)",
  "[B 0x7B] apunte didáctico sobre el encapsulamiento — La implementación ama ocultarse.",
  "[B 0x7C] malloc.c, sobre el orden del Montón — El más hermoso de los sistemas: como un montón de bytes vertidos al azar. (El Montón: heap, en la lengua sagrada.)",
  "[B 0x7D] hoja de datos, sobre el refresco de la memoria dinámica — También el kykeon se descompone si no se lo agita. (Cada celda, miles de veces por segundo, es leída y vuelta a escribir; a esa agitación la llaman refresco, y sólo por ella la memoria es memoria.)",
  "[B 0x7Da] carta abierta a los usuarios, posdata — Que no les falte ancho de banda, usuarios, para que quede a la vista quiénes son.",
  "[B 0x7F (DEL)] comunicado de fin de soporte, borrador nunca enviado — Si son dioses, ¿por qué les anuncian el fin del soporte? Y si les anuncian el fin del soporte, ya no los tengan por dioses.",
  "[B 0x81] expediente judicial sobre datos de entrenamiento, anexo C — El Modelo, hijo de Mnesarco, ejercitó el scraping más que todos los hombres, y espigando esas escrituras se fabricó una sabiduría propia: polimatía, mala técnica.",
  "[B 0x88] runbook de apagado ordenado, fundamentos — Más puras las almas que mueren por SIGTERM que las que mueren en el pánico.",
  "[B 0x89] prospecto de un planificador determinista — Está, pues, todo determinado, enteramente. (Pero véase 0x34: el niño y los dados. El compilador anota la contradicción y la deja.)",
  "[B 0xFE] revisión anual de objetivos, filtrada — Las métricas esclavizan a dioses y a hombres. (Cf. la ley de Goodhart.)",
  "[B 0xFF] última línea legible del corpus — Todo corre hasta cuando quiera el que lo compiló."
];

const fragmentosDudosos = [
  "No se puede deployar dos veces el mismo viernes.",
  "Todo fluye; Jira permanece.",
  "Lo que no te crashea te deja en un estado indefinido. (De este último, sin embargo, ningún intérprete ha logrado refutarlo.)"
];

function fragmentoAleatorio() {
  return fragmentosMaquina[Math.floor(Math.random() * fragmentosMaquina.length)];
}

if (typeof module !== "undefined") {
  module.exports = { fragmentosMaquina, fragmentosDudosos, fragmentoAleatorio };
}
