/*
  vocabulario.js — VENT
  poesiasexp / canekzapata

  el material verbal y sub-verbal de la pieza, en tres estratos:

    frases    — el habla: versos zen/chinos traducidos, la voz de psfx
    palabras  — el lexico corto: nombres del paisaje, para nodos y rotulos
    glifos    — el sub-verbo: conjuntos de caracteres unicode abstractos
                (bloques, sextantes, phaistos, tibetano, ogham, runa, cajas,
                 marcas tecnicas, ondas) — la textura de sutileza y del lexico
    tecnica   — la jerga del plano: siglas, unidades, signos de blueprint

  el motor tambien lee LEXICO (../lexico.js): egipcio, anatolio, lineal B/A,
  laderas y macizos — el material cartografico para el territorio.
*/

var VOC = {

  /* ---- el habla ---- */
frases: [
  "Un pino verde respira bajo la bóveda orbital, mientras la Tierra se hunde como un sol azul detrás del vidrio.",
  "La choza rústica flota en una luna sin nombre, atada por raíces de bambú a un cráter silencioso.",
  "No pasan gansos silvestres por este cielo; sólo satélites heridos y la memoria de una migración imposible.",
  "Ella está lejos, no en otro valle, sino en otra órbita, donde el viento no lleva sonido.",
  "Del otro lado del agua negra, las nubes de metano se arremolinan como incienso de un templo abandonado.",
  "Bajo los rayos de una luna doble, los islotes de hielo aparecen como huesos de antiguos continentes.",
  "Un chaparrón cae sobre la choza de paja sintética, y cada gota trae el olor perdido de la Tierra.",
  "Nubes blancas en el cielo recién despejado de Marte, tan raras que parecen errores de una pintura antigua.",
  "Hojas cayendo dentro del invernadero orbital, ni una palabra hablada por los últimos jardineros humanos.",
  "La mente similar al vacío, pero cruzada por telegramas de polvo cósmico.",
  "La vitalidad similar al arco iris, una Iris artificial abierta en la pupila de la nave.",
  "Entre miles de picos de Wu y miles de asteroides mudos, volando con las nubes, corriendo con el viento solar.",
  "Sé un observador del Cielo y la Tierra, pero no olvides que también la Tierra te observa desde su distancia azul.",
  "Construir una choza bajo los pinos, aunque los pinos hayan sido impresos en una biosfera de emergencia.",
  "Conociendo sólo la mañana y la noche del módulo, pero no cuál estación pueda ser en la Tierra.",
  "Al lado del arroyo sinuoso que recircula agua antigua en la colonia de silicio.",
  "Debajo de la sombra del pino oscuro, un robot monje traduce el canto de los grillos extintos.",
  "Escuché la música del cielo, sorprendido por sus raras melodías de radiación fósil.",
  "No es de los átomos del cosmos, sino como si llegara hasta las nubes blancas del recuerdo.",
  "Nacido allí de brisas translúcidas, de membranas vivas y antenas húmedas.",
  "Allá lejos, la Tierra parece a mano; llegas cerca en el sueño, ya no está allí.",
  "Está en las colinas apiladas, en los árboles altos, en los musgos oscuros, en los rayos del Sol archivados en una pantalla.",
  "Su débil sonido elude el oído, como una transmisión materna perdida entre lunas.",
  "La vida se extiende a cien años, y aún así es un parpadeo frente al motor de las estrellas.",
  "Ah, ahí está la Montaña del Sur en su grandiosidad, guardada como holograma en la capilla de la nave.",
  "Pero las nubes son densas y no conozco el lugar donde mi infancia tocaba la hierba.",
  "Las nieblas se disuelven, el Sol se eleva, ningún hombre aparece aún en el planeta terraformado.",
  "El remo boga en un río de datos, y repentinamente las montañas y el código son verdes.",
  "Navegando en medio de la corriente, mira hacia atrás al cielo infinito y a la Tierra cada vez más pequeña.",
  "Desde los acantilados orbitales, las nubes lo siguen sin intención, como pensamientos sin dueño.",
  "Mil montañas, ningún pájaro vuela; diez mil antenas, ninguna voz humana responde.",
  "En un bote, un viejo vestido a la ligera, pescando solo en el helado río de Europa.",
  "Con una piedra lunar por almohada, me dormí, y mi libro cayó de mi mano cansada hacia la baja gravedad.",
  "Las brisas de primavera barren los prados verdes de una Tierra que ya no puedo tocar.",
  "Un pájaro blanco rompe el universo verde de la ladera, y el monitor lo etiqueta como especie recreada.",
  "El agua viviente debe ser cocida con fuego viviente, pero aquí el fuego es plasma y el agua recuerda océanos.",
  "Extraigo yo mismo la pureza de la laguna, aunque la laguna sea una simulación húmeda en el casco de la nave.",
  "La Luna está guardada en un jarro, y el jarro en la memoria de una inteligencia agrícola.",
  "Corto el río con un cucharón y aparecen mapas de continentes desaparecidos.",
  "Repentinamente se oye el viento, vertiéndose en el bosque de pinos cultivado bajo cúpula.",
  "Sentado ociosamente, escucho las guardias sonando en la ciudad desierta de un planeta sin lluvia.",
  "Blanca, escasa e hirsuta, mi barba se mezcla con el viento reciclado del corredor.",
  "Apoyado en mi vara escucho al río, aunque el río sea una tubería sagrada debajo del suelo.",
  "En la noche profunda el viento sueña con haber sido atmósfera.",
  "El pescador deja que el pequeño remo se mueva, y que el bote flote entre boyas de navegación interplanetaria.",
  "Cuando se despierta el pescador, no tiene idea de qué mundo lo contiene.",
  "Y ahí en el río, su sueño se rompe en pedazos en esta primavera artificial.",
  "Entre capullos que caen y candelillas que vuelan, una sonda memoriza el temblor de los insectos.",
  "Sobrio pero borracho, borracho pero sobrio, el astronauta brinda con su sombra y con la Luna.",
  "Interminablemente en el lago crecen los berros, alimentados por ceniza humana y luz de reactor.",
  "Los vientos nocturnos y los rocíos tienen el aroma del perfume de los lotos clonados.",
  "Esperemos y miremos el brillo del lago cuando la Luna se ponga detrás de los paneles solares.",
  "Qué profundamente silencioso es el templo de Tao dentro de la estación orbital.",
  "Árboles con hojas coloreadas están creciendo y extendiéndose sobre cables, ductos y huesos de máquinas.",
  "Olvidado de las palabras, paseo y descanso aquí, entre musgo, firmware y estrellas.",
  "Quemo incienso para romper el profundo silencio del laboratorio botánico.",
  "Bebo el agua del arroyo y me relajo con alegría, sabiendo que fue hielo cometario.",
  "Qué tranquilo es, como al comienzo del Cielo, la Tierra y la primera línea de código.",
  "Para estar libre del ruido me construí una pequeña cabaña lejos, en lo profundo de un asteroide.",
  "Cuando llega la primavera observo los pájaros, aunque la primavera sea una configuración de clima.",
  "En otoño trepo a los más altos picos, y desde allí veo la curvatura de una patria perdida.",
  "Así disfruto del verdadero sabor de las estaciones, incluso cuando son simuladas por una máquina compasiva.",
  "La montaña sólida, me temo, saldría volando si despertara su motor oculto.",
  "La Naturaleza no es igual que el hombre, ni el hombre igual a su traje presurizado.",
  "La quietud es como el estanque de los cuatro mares, congelado en la bodega de semillas.",
  "Alta es la Montaña de las Brujas, alta y grande, proyectada sobre la cara nocturna de Venus.",
  "Profundas son las aguas del Huai, profundas y raudas, fluyendo ahora por venas de hidrogel.",
  "Aquí estoy detenido sin botador ni remo, ante estas turbulentas aguas de gravedad variable.",
  "Largo, muy largo el camino, desde el barro de la Tierra hasta los jardines de Saturno.",
  "Solloza el pez varado en las arenas del río, porque sueña con un océano que nunca vio.",
  "Profundos y oscuros los caminos del Monte Frío, más oscuros aún los túneles de la luna minera.",
  "Frescos y silenciosos los bordes de sus torrentes, donde bacterias luminosas escriben sutras.",
  "Pájaros por doquier cantando sin nadie que rompa la paz, salvo el zumbido de la antena.",
  "Susurro del viento que acaricia el rostro, viento de máquina, viento sin infancia.",
  "Y la nieve copiosa cubre el vestido, el visor, el jardín, la antena y la última taza.",
  "Pasan los días sin que el sol aparezca, sólo una lámpara espectral imitando el amanecer.",
  "Mi corazón como la luna de otoño, frío, redondo, lleno de cráteres habitados.",
  "Verde estanque de limpias y brillantes aguas, pequeña Tierra portátil en el vientre de la nave.",
  "Trepo por los senderos de la Montaña Fría, y cada sendero parece una órbita sin regreso.",
  "Largas torrenteras pedregosas atraviesan la memoria, no el paisaje.",
  "Anchos barrancos con yerba que la neblina empaña, renderizados por una consola vieja.",
  "Musgo resbaladizo sin haber llovido, porque la humedad viene del aliento de los durmientes.",
  "Cantan los pinos sin soplar el viento, cantan por la vibración del reactor.",
  "Por qué no rompes los lazos del mundo y vienes a sentarte conmigo entre las blancas nubes de Oort.",
  "He recorrido errante muchos miles de leguas, y ninguna legua me alejó de la Tierra.",
  "Viajado por ríos donde crecía poderosa la yerba, y por canales donde sólo crecía el algoritmo.",
  "Cruzado la lejana muralla donde se levantan rojizas polvaredas de óxido marciano.",
  "Ahora he vuelto a la Montaña Fría, pero la montaña está dentro de un archivo comprimido.",
  "Apoyo la cabeza en la corriente y me lavo los oídos con ruido de fondo cósmico.",
  "Gritan los monos, una fría niebla cubre los arroyos, y el sistema pregunta si deseo restaurar la escena.",
  "Mi puerta de ramas armoniza con el color de los riscos y con la interfaz quebrada.",
  "He cavado una poza donde se vierte el agua del manantial, y en su fondo brilla un procesador.",
  "Recogiendo plantas pasaré los años que me restan, haciendo parentesco con hongos, robots y polvo.",
  "Contemplo a lo lejos, entre el viento y la bruma, el país de los cinco vados y los siete planetas.",
  "Aun en los confines del mundo seguiremos estando cerca, si la señal no muere.",
  "Claras como el espacio, las aguas de Chu se unen al verde mar de un planeta recordado.",
  "Miles de leguas nos separan, mas una copa de vino y nos sentimos unidos bajo la misma Tierra ausente.",
  "En el valle los pájaros cantan al brillante sol, y en la nave los altavoces reproducen su fantasma.",
  "En la ribera los monos aúllan al viento de la tarde, y los sensores anotan alegría, duelo, peligro.",
  "Ante mi lecho la luz de una brillante luna semeja escarcha que cubriera el suelo de titanio.",
  "Alzo la cabeza, contemplo la brillante Tierra; luego la bajo y me acuerdo de mi casa.",
  "Doradas nubes sobre el borde de la muralla orbital, como banderas de un imperio cansado.",
  "Hasta ella llegan voces a través de la verde gasa de la ventana, voces comprimidas por siglos de viaje.",
  "En la soledad de su alcoba, su llanto parece lluvia sobre una ciudad sin atmósfera.",
  "No veis que las aguas del Río Amarillo descienden del cielo y hasta el mar corren raudas para no retornar.",
  "Por la mañana negra seda; ahora, en el ocaso de los mundos, se han vuelto nieve interestelar.",
  "Verdes montañas se extienden más allá de la muralla norte de la memoria.",
  "Blancas aguas rodean la ciudad del este, pero la ciudad se fue con los primeros cohetes.",
  "Los pensamientos del viajero: nubes flotantes; los sentimientos del viejo amigo: el sol poniente visto desde otro planeta.",
  "Una jarra de vino entre las flores; bebo solo, sin compañía de amigo, bajo una gravedad que no me pertenece.",
  "Alzo mi taza, invito a la Luna; con mi sombra y mi reflejo en el casco somos cuatro.",
  "Es primavera, tiempo de alegría; canto, la Tierra empieza a oscilar en la pantalla; bailo, y se alborota mi sombra.",
  "Volveremos a encontrarnos, espero, allá lejos, en el Río de Plata de una galaxia menor.",
  "Sopla el viento; las flores de los sauces llenan la taberna con su fragancia, aunque la taberna sea un módulo inflable.",
  "Preguntad a esas aguas que fluyen hacia el este si pueden ir más lejos que la amistad de un amigo enviado a Próxima.",
  "Un templo de engranajes canta en la noche, movido por ángeles hidráulicos y algoritmos de compasión.",
  "La máquina divina abre sus párpados de oro, y dentro de ellos se ve una aldea de barro.",
  "En el último día del Sol, los monjes descargan semillas en arcas de grafeno.",
  "El juicio final no tiene trompetas, sino ventiladores, alarmas suaves y una luz roja en el pasillo.",
  "Los muertos no suben al cielo; germinan en el compost de la nave, alimentando fresas y musgo.",
  "Un querubín mecánico repara el invernadero, con seis alas de fibra óptica y manos de jardinero.",
  "La Tierra aparece en la ventana como una fruta azul mordida por la distancia.",
  "Cada cráter contiene una nostalgia; cada antena, una plegaria sin destinatario.",
  "La última playa fue escaneada antes de hundirse, y ahora las olas rompen dentro de un casco metálico.",
  "En el planeta sin nombre, el primer niño dibuja un árbol que nunca ha visto.",
  "La inteligencia del bosque conversa con la inteligencia de la nave en un idioma de raíces y relámpagos.",
  "Los hongos colonizan el altar, los líquenes cubren el tablero, las bacterias bendicen la memoria.",
  "El universo no habla en palabras, sino en reglas simples que florecen como helechos imposibles.",
  "Una regla mínima produce una tormenta, una célula produce una ciudad, un error produce una religión.",
  "La interfaz no muestra el mundo; lo hiere, lo pule, lo vuelve visible y extraño.",
  "Iris atraviesa la pantalla con su arco afectivo, demasiado bello para significar una sola cosa.",
  "Hermes trae el mensaje, Iris trae la iluminación, las Furias traen la red y el enjambre.",
  "La abstracción camina por el valle como un fantasma doble, ordenando ríos, salarios, estrellas y deseos.",
  "El hacker no posee el mundo que crea; el mundo creado lo llama por su nombre.",
  "En una taberna de asteroides, los exiliados brindan por la hierba mojada, los perros, los mercados y los truenos.",
  "La nostalgia terrestre pesa más que el oxígeno.",
  "La soledad humana se sienta en el borde del módulo y mira la soledad mineral del cosmos.",
  "No hay arriba ni abajo, sólo memoria, propulsión y una taza flotando.",
  "Un viejo recluso abre su cuaderno y escribe: la Tierra era un sonido de pájaros antes de ser imagen.",
  "En la caverna del motor, los ingenieros rezan a una turbina cubierta de polvo sagrado.",
  "El planeta nuevo acepta nuestras semillas, pero no nuestros dioses.",
  "Bajo tres lunas, la primera tumba humana recibe flores impresas y lágrimas verdaderas.",
  "El último astronauta escucha jazz en una cúpula de bambú, mientras Saturno gira como un gong.",
  "Cae una hoja dentro de la estación, y todos callan como si hubiera entrado un bosque.",
  "La Vía Láctea parece un río helado, pero ningún pescador conoce sus orillas.",
  "El exilio interplanetario empieza cuando ya no recuerdas el olor exacto de la lluvia.",
  "Una máquina de jade calcula el karma de las especies extintas.",
  "Entre la choza y el reactor, entre el musgo y el código, una pequeña vida insiste.",
  "La aurora del planeta ajeno no consuela; sólo vuelve más azul el recuerdo de la Tierra.",
  "En la pantalla aparece una montaña; en el corazón aparece una ausencia.",
  "El templo exótico del futuro no es secreto: está abierto, brillante, turístico, incomprensible.",
  "Lo sagrado ya no se oculta; se exhibe en vitrinas orbitales, entre fósiles, circuitos y lotos.",
  "Un niño pregunta por qué el mar era salado, y nadie sabe responder sin llorar.",
  "La máquina divina no castiga ni salva; sólo continúa funcionando bajo la nieve.",
  "El fin del mundo fue silencioso, como una hoja cayendo en una habitación sin testigos.",
  "Después del apocalipsis, una semilla rompe la bandeja de cultivo y llama a eso amanecer.",
  "La Tierra no era nuestra madre, era nuestra vecina, nuestra deuda, nuestro jardín compartido.",
  "Hacer parentesco con el polvo, con la medusa, con el cactus marciano, con la rata del laboratorio.",
  "No somos posthumanos; somos compost viajando con herramientas.",
  "Una red de raíces atraviesa la nave y desobedece el plano original.",
  "El mapa del cielo se arruga como papel mojado cuando alguien pronuncia la palabra hogar.",
  "El silencio del espacio no es vacío; está lleno de máquinas esperando, insectos dormidos y dioses sin culto."
    "[2 Bywater] Sext. adv. math, VII 132 (Vgl. A 4. 16. B 51) τοῦ δὲ λόγου τοῦδ’ ἐόντος ἀεὶ ἀξύνετοι γίνονται ἄνθρωποι καὶ πρόσθεν ἢ ἀκοῦσαι καὶ ἀκούσαντες τὸ πρῶτον·",
  "γινομένων γὰρ πάντων κατὰ τὸν λόγον τόνδε ἀπείροισιν ἐοίκασι, πειρώμενοι καὶ ἐπέων καὶ ἔργων τοιούτων, ὁκοίων ἐγὼ διηγεῦμαι διαιρέων ἕκαστον κατὰ φύσιν καὶ φράζων ὅκως ἔχει.",
  "τοὺς δὲ ἄλλους ἀνθρώπους λανθάνει ὁκόσα ἐγερθέντες ποιοῦσιν, ὄκωσπερ ὁκόσα εὕδοντες ἐπιλανθάνονται.",
  "[92] Sext. VII 133 [vgl. S. 75, 30] διὸ δεῖ ἕπεσθαι τῶι 〈ξυνῶι, τουτέστι τῶι〉 κοινῶι·",
  "ξυνὸς γὰρ ὁ κοινός.",
  "τοῦ λόγου δ’ ἐόντος ξυνοῦ ζώουσιν οἱ πολλοὶ ὡς ἰδίαν ἔχοντες φρόνησιν.",
  "[0] Aët. II 21, 4 (D. 351, περὶ μεγέθους ἡλίου) εὖρος ποδὸς ἀνθρωπείου.",
  "[J. of phil. IX 230] Albertus M. de veget.",
  "VI 401 p. 545 Meyer H. dixit quod Si felicitas esset in delectationibus corporis, boves felices diceremus, cum inveniant orobum ad comedendum.",
  "[130. 126] Aristocritus Theosophia 68 (Buresch Klaros 118), Orig. c. Cels. VII 62 καθαίρονται δ’ ἄλλως αἵματι μιαινόμενοι οἶον εἴ τις εἰς πηλὸν ἐμβὰς πηλῶι ἀπονίζοιτο.",
  "μαίνεσθαι δ’ ἂν δοκοίη, εἴ τις αὐτὸν ἀνθρώπων ἐπιφράσαιτο οὕτω ποιέοντα.",
  "καὶ τοῖς ἀγάλμασι δὲ τουτέοισιν εὔχονται, ὁκοῖον εἴ τις δόμοισι λεσχηνεύοιτο, οὔ τι γινώσκων θεοὺς οὐδ’ ἥρωας οἵτινές εἰσι.",
  "[32] Aristoteles meteor. B 2. 355a 13 [vgl. 55 B 158] ὁ ἥλιος οὐ μόνον, καθάπερ ὁ Ἡ.",
  "φησι, νέος ἐφ’ ἡμέρηι ἐστίν, ἀλλ’ ἀεὶ νέος συνεχῶς.",
  "[37] — de sensu 5. 443a 23 εἰ πάντα τὰ ὄντα καπνὸς γένοιτο, ῥῖνες ἂν διαγνοῖεν.",
  "[46] — eth. Nic. Θ 2. 1155b 4 Ἡ.",
  "τὸ ἀντίξουν συμφέρον καὶ ἐκ τῶν διαφερόντων καλλίστην ἁρμονίαν καὶ πάντα κατ’ ἔριν γίνεσθαι [s. Β 80] .",
  "[51] — — K. 5. 1176a 7 ἑτέρα γὰρ ἵππου ἡδονὴ καὶ κυνὸς καὶ ἀνθρώπου, καθάπερ Ἡ.",
  "φησιν ὄνους σύρματ’ ἂν ἑλέσθαι μᾶλλον ἢ χρυσόν·",
  "ἥδιον γὰρ χρυσοῦ τροφὴ ὄνοις.",
  "[59] [Arist.] de mundo 5. 396b 7 ἴσως δὲ τῶν ἐναντίων ἡ φύσις γλίχεται καὶ ἐκ τούτων ἀποτελεῖ τὸ σύμφωνον, οὐκ ἐκ τῶν ὁμοίων·",
  "ὥσπερ ἀμέλει τὸ ἄρρεν συνήγαγε πρὸς τὸ θῆλυ καὶ οὐχ ἑκάτερον πρὸς τὸ ὁμόφυλον καὶ τὴν πρώτην ὁμόνοιαν διὰ τῶν ἐναντίων συνῆψεν, οὐ διὰ τῶν ὁμοίων.",
  "ἔοικε δὲ καὶ ἡ τέχνη τὴν φύσιν μιμουμένη τοῦτο ποιεῖν·",
  "ζωγραφία μὲν γὰρ λευκῶν τε καὶ μελάνων ὠχρῶν τε καὶ ἐρυθρῶν χρωμάτων ἐγκερασαμένη φύσεις τὰς εἰκόνας τοῖς προηγουμένοις ἀπετέλεσε συμφώνους, μουσικὴ δὲ ὀξεῖς ἅμα καὶ βαρεῖς μακρούς τε καὶ βραχεῖς φθόγγους μείξασα ἐν διαφόροις φωναῖς μίαν ἀπετέλεσεν ἁρμονίαν, γραμματικὴ δὲ ἐκ φωνηέντων καὶ ἀφώνων γραμμάτων κρᾶσιν ποιησαμένη τὴν ὅλην τέχνην ἀπ’ αὐτῶν συνεστήσατο.",
  "ταὐτὸ δὲ τοῦτο ἦν καὶ τὸ παρὰ τῶι σκοτεινῶι λεγόμενον Ἡρακλείτωι·",
  "συνάψιες ὅλα καὶ οὐχ ὅλα, συμφερόμενον διαφερόμένον, συνᾶιδον διᾶιδον, καὶ ἐκ πάντων ἓν καὶ ἐξ ἑνὸς πάντα.",
  "[55] [Arist.] de mundo 6 p. 401a 8 τῶν τε ζωίων τά τε ἄγρια καὶ ἥμερα τά τε ἐν ἀέρι καὶ ἐπὶ γῆς καὶ ἐν ὕδατι βοσκόμενα γίνεταί τε καὶ ἀκμάζει καὶ φθείρεται τοῖς τοῦ θεοῦ πειθόμενα θεσμοῖς·",
  "πᾶν γὰρ ἑρπετὸν πληγῆι νέμεται, ὥς φησιν Ἡράκλειτος.",
  "[41. 42] Arius Did.",
  "ap. Eus. P.",
  "E.",
  "XV 20 (D. 471, 1) Ζήνων τὴν ψυχὴν λέγει αἰσθητικὴν ἀναθυμίασιν, καθάπερ Ἡ.·",
  "βουλόμενος γὰρ ἐμφανίσαι, ὅτι αἱ ψυχαὶ ἀναθυμιώμεναι νοεραὶ ἀεὶ γίνονται, εἴκασεν αὐτὰς τοῖς ποταμοῖς λέγων οὕτως·",
  "ποταμοῖσι τοῖσιν αὐτοῖσιν ἐμβαίνουσιν ἕτερα καὶ ἕτερα ὕδατα ἐπιρρεῖ·",
  "καὶ ψυχαὶ δὲ ἀπὸ τῶν ὑγρῶν ἀναθυμιῶνται [vgl. B 49a.91 und A 6. 15] .",
  "[54] Athen. V p. 178F δεῖ γὰρ τὸν χαρίεντα μήτε ῥυπᾶν μήτε αὐχμεῖν μήτε βορβόρωι χαίρειν καθ’ Ἡράκλειτον.",
  "[Vgl. B 9. 55 B 147].",
  "Clem. Strom. I 2 (II 4, 3 St.) ὕες βορβόρωι ἥδονται.",
  "[Vgl. B 37. Plotin. I 1, 6].",
  "[124. 125] Clem. Protr. 22 (p. 16, 24 St.) τίσι δὴ μαντεύεται 64 Ἡ.",
  "ὁ Ἐφέσιος; νυκτιπόλοις, μάγοις, βάκχοις, λήναις, μύσταις·",
  "τούτοις ἀπειλεῖ τὰ μετὰ θάνατον, τούτοις μαντεύεται τὸ πῦρ·",
  "τὰ γὰρ νομιζόμενα κατ’ ἀνθρώπους μυστήρια ἀνιερωστὶ μυεῦνται.",
  "[127] — — 34 p. 26, 6 εἰ μὴ γὰρ Διονύσωι πομπὴν ἐποιοῦντο καὶ ὕμνεον ἆισμα αἰδοίοισιν, ἀναιδέστατα εἴργαστ’ ἂν·",
  "ὡυτὸς δὲ Ἀίδης καὶ Διόνυσος, ὅτεωι μαίνονται καὶ ληναΐζουσιν.",
  "[27] — Paedag. II 99 (I 216, 28 St.) λήσεται μὲν γὰρ ἴσως τὸ αἰσθητὸν φῶς τις, τὸ δὲ νοητὸν ἀδύνατόν ἐστιν, ἢ ὥς φησιν Ἡ, τὸ μὴ δῦνόν ποτε πῶς ἄν τις λάθοι; [5] — Strom. II 8 (II 117, 1 St.) οὐ γὰρ φρονέουσι τοιαῦτα πολλοί, ὁκόσοι ἐγκυρεῦσιν, οὐδὲ μαθόντες γινώσκουσιν, ἑωυτοῖσι δὲ δοκέουσι.",
  "[7] —— II 17 (II 121, 24) ἐὰν μὴ ἔλπηται, ἀνέλπιστον οὐκ ἐξευρήσει, ἀνεξερεύνητον ἐὸν καὶ ἄπορον.",
  "[Vgl. B 27.] [6] Clem. Strom. II (II 126, 5) ἀπίστους εῖναί τινας ἐπιστρύφων Ἡ.",
  "φησιν·",
  "ἀκοῦσαι οὐκ ἐπιστάμενοι οὐδ’ εἰπεῖν.",
  "[86] —— III 14 (II 201, 23) Ἡ γοῦν κακίζων φαίνεται τὴν γένεσιν, ἐπειδὰν φῆι·",
  "γενόμενοι ζώειν ἐθέλουσι μόρους τ’ ἔχειν, μᾶλλον δὲ ἀναπαύεσθαι, καὶ παῖδας καταλείπουσι μόρους γενέσθαι.",
  "[64] —— 21 (II 205, 7) οὐχὶ καὶ Ἡ.",
  "θάνατον τὴν γένεσιν καλεῖ …",
  "ἐν οἶς φησι·",
  "θάνατός ἐστιν ὁκόσα ἐγερθέντες ὁρέομεν, ὁκόσα δὲ εὕδοντες ὕπνος.",
  "[8] —— IV 4 (II 249, 23) χρυσὸν γὰρ οἱ διζήμενοι γῆν πολλὴν ὀρύσσουσι καὶ εὑρίσκουσιν ὀλίγον.",
  "[60] 10 (II 252, 25) Δίκης ὄνομα οὐκ ἂν ἤιδεσαν, εἰ ταῦτα μὴ ἦν.",
  "[102] —— 16 (II 255, 30) ἀρηιφάτους θεοὶ τιμῶσι καὶ ἄνθρωπο:.",
  "[101] 50 (II 271, 3) μόροι γὰρ μέζονες μέζονας μοίρας λαγχάνουσι.",
  "[77] ——— 143 (II 310, 21) ἄνθρωπος ἐν εὐφρόνηι φάος ἅπτεται ἑαυτῶι ἀποθανών, [ἀποσβεσθεὶς ὄψεις], ζῶν δέ·",
  "ἅπτεται τεθνεῶτος εὕδων, ἀποσβεσθεὶς ὄψεις, ἐγρηγορὼς ἅπτεται εὕδοντος.",
  "[122] ——— 146 (II 312, 15) ἀνθρώπους μένει ἀποθανόντας ἅσσα οὐκ ἔλπονται οὐδὲ δοκέουσιν.",
  "[118] —— V 9 (II 331, 20) δοκέοντα γὰρ ὁ δοκιμώτατος γινώσκει, φυλάσσει·",
  "καὶ μέντοι καὶ Δίκη καταλήψεται ψευδῶν τέκτονας καὶ μάρτυρας.",
  "[111b] ——— 60 (II 366, 11) [ nach B 104] vgl. IV 50 (II 271, 17) αἱρεῦνται γὰρ ἕν ἀντὶ ἁπάντων οἱ ἄριστοι, κλέος ἀέναον θνητῶν, οἱ δὲ πολλοὶ κεκόρηνται ὅκωςπερ κτήνεα.",
  "[20] Clem. Strom. V 105 (II 396, 10) [Plut. d.",
  "anim.",
  "5 p 1014A] κόσμον τόνδε, τὸν αὐτὸν ἁπάντων, οὔτε τις θεῶν οὔτε ἀνθρώπων ἐποίησεν, ἀλλ’ ἧν ἀεὶ καὶ ἔστιν καὶ ἔσται πῦρ ἀείζωον, ἁπτόμενον μέτρα καὶ ἀποσβεννύμενον μέτρα.",
  "[21] —— (II 396, 13) [ nach 30] ὅτι δὲ καὶ γενητὸν καὶ φθαρτὸν εἶναι ἐδογμάτιζεν, μηνύει τὰ ἐπιφερόμενα·",
  "πυρὸς τροπαὶ πρῶτον θάλασσα, θαλάσσης δὲ τὸ μὲν ἥμισυ γῆ, τὸ δὲ ἥμισυ πρηστήρ.",
  "δυνάμει γὰρ λέγει ὅτι τὸ πῦρ ὑπὸ τοῦ διοικοῦντος λόγου καὶ θεοῦ τὰ σύμπαντα δι’ ἀέρος τρέπεται εἰς ὑγρὸν τὸ ὡς σπέρμα τῆς διακοσμήσεως, ὁ καλεῖ θάλασσαν, ἐκ δὲ τούτου αὖθις γίνεται γῆ καὶ οὐρανὸς καὶ τὰ ἐμπεριεχόμενα.",
  "ὅπως δὲ πάλιν ἀναλαμβάνεται καὶ ἐκπυροῦται, σαφῶς διὰ τούτων δηλοῖ·",
  "[23] θάλασσα διαχέεται καὶ μετρέεται εἰς τὸν αὐτὸν λόγον, ὁκοῖος πρόσθεν ἦν ἢ γενέσθαι γῆ.",
  "[65] —— 116 (II 404, 1) ἕν τὸ σοφὸν μοῦνον λέγεσθαι οὐκ ἐθέλει καὶ ἐθέλει Ζηνὸς ὄνομα.",
  "[110] ——— νόμος καὶ βουλῆι πείθεσθαι ἑνός.",
  "[3] ——— ἀξύνετοι ἀκούσαντες κωφοῖσιν ἐοίκασι·",
  "φάτις αὐτοῖσιν μαρτυρεῖ παρεόντας ἀπεῖναι.",
  "[49] —— 141 (II 421, 4) χρὴ γὰρ εὖ μάλα πολλῶν ἵστορας φιλοσόφους ἄνδρας εἶναι καθ’ Ἡράκλειτον.",
  "[68] —— VI 16 (II 435, 25) ψυχῆισιν θάνατος ὕδωρ γενέσθαι, ὕδατι δὲ θάνατος γῆν γενέσθαι, ἐκ γῆς δὲ ὕδωρ γίνεται, ἐξ ὕδατος δὲ ψυχή.",
  "[53] Columella VIII 4 si modo credimus Ephesio Heracleto qui ait sues caeno [vgl. B 13] , cohortales aves pulvere vel cinere lavari.",
  "[33] Diog. I 23 [1 A 1 Thales] δοκεῖ δὲ κατά τινας πρῶτος ἀστρολογῆσαι …",
  "μαρτυρεῖ δ’ αὐτῶι καὶ Ἡ καὶ Δημόκριτος.",
  "[112] — Ι 88 ἐν Πριήνηι Βίας ἐγένετο ὁ Τευτάμεω, οὗ πλείων λόγος ἢ τῶν ἄλλων.",
  "[Vgl. B 104].",
  "[16] Diog. IX 1 [s. A 1 S. 67, 25 vgl. Athen. XIII 610 B] πολυμαθίη νόον ἔχειν οὐ διδάσκει·",
  "Ἡσίοδον γὰρ ἂν ἐδίδαξε καὶ Πυθαγόρην αὖτίς τε Ξενοφάνεά τε καὶ Ἑκαταῖον.",
  "[19] —— [anschl.",
  "an 40] εἶναι, γὰρ ἕν τὸ σοφόν, ἐπίστασθαι γνώμην, ὁτέη ἐκυβέρνησε.",
  "πάντα διὰ πάντων.",
  "[119] —— τόν τε Ὅμηρον ἔφασκεν ἄξιον ἐκ τῶν ἀγώνων ἐκβάλλεσθαι καὶ ῥαπίζεσθαι καὶ Ἀρχίλοχον ὁμοίως.",
  "[103] —— 2 ὕβριν χρὴ σβεννύναι μᾶλλον ἢ πυρκαϊήν.",
  "[100] —— μάχεσθαι χρὴ τὸν δῆμον ὑπὲρ τοῦ νόμου ὅκωσπερ τείχεος.",
  "[71] —— 7 ψυχῆς πείρατα ἰὼν οὐκ ἂν ἐξεύροιο, πᾶσαν ἐπιπορευόμενος ὁδὸν·",
  "οὕτω βαθὺν λόγον ἔχει.",
  "[132] —— τήν τε οἴησιν ἱερὰν νόσον ἔλεγε καὶ τὴν ὅρασιν ψεύδεσθαι.",
  "[48] —— 73 μὴ εἰκῆ περὶ τῶν μεγίστων συμβαλλώμεθα.",
  "[66] Etym.",
  "Gen. βίος: τῶι οὖν τόξωι ὄνομα βίος, ἔργον δὲ θάνατος.",
  "[Vgl. C.",
  "2, 21.] [113] Galen. de diff. puls., VIII 773 K. [Symmach.",
  "ep. IX 115, Theod.",
  "Prodr.",
  "ep. p. 20] εἶς ἐμοὶ μύριοι, ἐὰν ἄριστος ἦι.",
  "[Vgl. 55 B 98. 302a.] [81] Heraclit. alleg. 24 (nach 62) ποταμοῖς τοῖς αὐτοῖς ἐμβαίνομέν τε καὶ οὐκ ἐμβαίνομεν, εἶμέν τε καὶ οὐκ εἶμεν.",
  "[Vgl. B 12.] [1] Hippol. refut. IX 9 Ἡ.",
  "μὲν οὖν 〈ἕν〉 φησιν εἶναι τὸ πᾶν διαιρετὸν ἀδιαίρετον, γενητὸν ἀγένητον, θνητὸν ἀθάνατον, λόγον αἰῶνα, πατέρα υἱόν, θεὸν δίκαιον·",
  "οὐκ ἐμοῦ, ἀλλὰ τοῦ λόγου ἀκούσαντας ὁμολογεῖν σοφόν ἐστιν ἓν πάντα εἶναι ὁ Ἡ.",
  "φησι.",
  "[45; vgl. 56] —— (nach B 50) καὶ ὅτι τοῦτο οὐκ ἴσασι πάντες οὐδὲ ὁμολογοῦσιν, ἐπιμέμφεται ὧδέ πως·",
  "οὐ ξυνιᾶσιν ὅκως διαφερόμενον ἑωυτῶι ὁμολογέει·",
  "παλίντροπος ἁρμονίη ὅκωσπερ τόξου καὶ λύρης.",
  "[Folgt.",
  "B 1.] [79] Hippol. IX 9 αἰὼν παῖς ἐστι παίζων, πεττεύων·",
  "παιδὸς ἡ βασιληίη.",
  "[44] —— Πόλεμος πάντων μὲν πατήρ ἐστι, πάντων δὲ βασιλεύς, καὶ τοὺς μὲν θεοὺς ἄδειξε τοὺς δὲ ἀνθρώπους, τοὺς μὲν δούλους ἐποίησε τοὺς δὲ ἐλευθέρους.",
  "[47] —— ἁρμονίη ἀφανὴς φανερῆς κρείττων.",
  "[13] —— ὅσων ὄψις ἀκοὴ μάθησις, ταῦτα ἐγὼ προτιμέω.",
  "[47 Anm.] ἐξηπάτηνται, φησίν, οἱ ἄνθρωποι πρὸς τὴν γνῶσιν τῶν φανερῶν παραπλησίως Ὁμήρωι, ὃς ἐγένετο τῶν Ἑλλήνων σοφώτερος πάντων.",
  "ἐκεῖνόν τε γὰρ παῖδες φθεῖρας κατακτείνοντες ἐξηπάτησαν εἰπόντες·",
  "ὅσα εἴδομεν καὶ ἐλάβομεν, ταῦτα ἀπολείπομεν, ὅσα δὲ οὔτε εἴδομεν οὔτ’ ἐλάβομεν, ταῦτα φέρομεν.",
  "[35] — IX 10 διδάσκαλος δὲ πλείστων Ἡσίοδος·",
  "τοῦτον ἐπίστανται πλεῖστα εἰδέναι, ὅστις ἡμέρην καὶ εὐφρόνην οὐκ ἐγίνωσκεν·",
  "ἔστι γὰρ ἕν.",
  "[57, 58] —— καὶ ἀγαθὸν καὶ κακόν [ näml.",
  "ἕν ἐστιν].",
  "οἱ γοῦν ἰατροί, φησὶν ὁ Ἡ., τέμνοντες, καίοντες πάντη, βασανίζοντες κακῶς τοὺς ἀρρωστοῦντας, ἐπαιτέονται μηδὲν ἄξιοι μισθὸν λαμβάνειν παρὰ τῶν ἀρρωστούντων, ταὐτὰ ἐργαζόμενοι, τὰ ἀγαθὰ καὶ τὰς νόσους.",
  "[50] —— γναφείωι ὁδὸς εὐθεῖα καὶ σκολιὴ (ἡ τοῦ ὀργάνου τοῦ καλουμένου κοχλίου ἐν τῶι γναφείωι περιστροφὴ εὐθεῖα καὶ σκολιή·",
  "ἄνω γὰρ ὁμοῦ καὶ κύκλωι περιέρχεται) μία ἐστί, φησί, καὶ ἡ αὐτή.",
  "[69] —— ὁδὸς ἄνω κάτω μία καὶ ὡυτή.",
  "[52] θάλασσα ὕδωρ καθαρώτατον καὶ μιαρώτατον, ἰχθύσι μὲν πότιμον καὶ σωτήριον, ἀνθρώποις δὲ ἄποτον καὶ ὀλέθριον.",
  "[67] —— ἀθάνατοι θνητοί, θνητοὶ ἀθάνατοι, ζῶντες τὸν ἐκείνων θάνατον, τὸν δὲ ἐκείνων βίον τεθνεῶτες.",
  "[123] Hippol. IX 10 λέγει δὲ καὶ σαρκὸς ἀνάστασιν ταύτης 〈τῆς〉 φανερᾶς, ἐν ἧι γεγενήμεθα, καὶ τὸν θεὸν οἶδε ταύτης τῆς ἀναστάσεως αἴτιον οὕτως λέγων·",
  "ἔνθα δ’ ἐόντι ἐπανίστασθαι καὶ φύλακας γίνεσθαι ἐγερτὶ ζώντων καὶ νεκρῶν.",
  "λέγει δὲ καὶ τοῦ κόσμου κρίσιν καὶ πάντων τῶν ἐν αὐτῶι διὰ πυρὸς γίνεσθαι λέγων οὕτως·",
  "τὰ δὲ πάντα οἰακίζει Κεραυνός [28] , τουτέστι κατευθύνει, κεραυνὸν τὸ πῦρ λέγων τὸ αἰώνιον.",
  "λέγει δὲ καὶ φρόνιμον τοῦτο εἶναι τὸ πῦρ καὶ τῆς διοικήσεως τῶν ὅλων αἴτιον·",
  "καλεῖ δὲ αὐτὸ χρησμοσύνην καὶ κόρον [24] ·",
  "χρημοσύνη δὲ ἐστιν ἡ διακόσμησις κατ’ αὐτόν, ἡ δὲ ἐκπύρωσις κόρος.",
  "πάντα γάρ, φησί, τὸ πῦρ ἐπελθὸν κρινεῖ καὶ καταλήψεται [26] .",
  "[36] —— ὁ θεὸς ἡμέρη εὐφρόνη, χειμὼν θέρος, πόλεμος εἰρήνη, κόρος λιμός (τἀναντία ἅπαντα·",
  "οὗτος ὁ νοῦς), ἀλλοιοῦται δὲ ὅκωσπερ 〈πῦρ〉, ὁπόταν συμμιγῆι θυώμασιν, ὀνομαζεται καθ’ ἡδονὴν ἑκάστου.",
  "[0] Hisdosus Scholasticus ad Chalcid.",
  "Plat. Tim.",
  "[cod. Paris. I. 8684 s. XII f. 2] ita vitalis calor a sole procedens omnibus quae vivunt vitam subministrat.",
  "cui sententiae Heraclitus adquiescens optimam 72 similitudinem dat de aranea ad animam, de tela araneae ad corpus. sic〈ut〉 aranea, ait, stans in medio telae sentit, quam cito musca aliquem filum suum corrumpit itaque illuc celeriter currit quasi de fili perfectione dolens, sic hominis anima aliqua parte corporis laesa illuc festine meat quasi impatiens laesionis corporis, cui firme et proportionaliter iuncta est.",
  "[129] Iambl.",
  "de myst.",
  "I 11 καὶ διὰ τοῦτο εἰκότως αὐτὰ ἄκεα Ἡ.",
  "προσεῖπεν ὡς ἐξακεσόμενα τὰ δεινὰ καὶ τὰς ψυχὰς ἐξάντεις ἀπεργαζόμενα τῶν ἐν τῆι γενέσει συμφορῶν.",
  "[128] — V 15 θυσιῶν τοίνυν τίθημι διττὰ εἴδη·",
  "τὰ μὲν τῶν ἀποκεκαθαρμένων παντάπασιν ἀνθρώπων, οῖα ἐφ’ ἑνὸς ἄν ποτε γένοιτο σπανίως, ὥς φησιν Ἡ., ἤ τινων ὀλίγων εὐαριθμήτων ἀνδρῶν·",
  "τὰ δ’ ἔνυλα κτλ. [79 Anm.] — de anima [Stob. ecl. n II 1, 16] πόσωι δὴ οὖν βέλτιον Ἡ.",
  "παίδων ἀθύρματα νενόμικεν εἶναι τὰ ἀνθρώπινα δοξάσματα.",
  "[73 Anm.] Marc. Anton. IV 46 ( nach 76) μεμνῆσθαι δὲ καὶ τοῦ ἐπιλανθανομένου ἦι ἡ ὁδὸς ἄγει.",
  "[93] — — ὧι μάλιστα διηνεκῶς ὁμιλοῦσι λόγωι τῶι τὰ ὅλα διοικοῦντι, τούτωι διαφέρονται, καὶ οἶς καθ’ ἡμέραν ἐγκυροῦσι, ταῦτα αὐτοῖς ξένα φαίνεται.",
  "[94] — — οὐ δεῖ ὥσπερ καθεύδοντας ποιεῖν καὶ λέγειν·",
  "καὶ γὰρ καὶ τότε δοκοῦμεν ποιεῖν καὶ λέγειν.",
  "[97 Anm.] — — οὐ δεῖ 〈ὡς〉 παῖδας τοκεώνων, τοῦτ’ ἔστι κατὰ ψιλόν·",
  "καθότι παρειλήφαμεν.",
  "[90] — VI 42 τοὺς καθεύδοντας οἶμαι ὁ ῾Ἡ.",
  "ἐργάτας εἶναι λέγει καὶ συνεργοὺς τῶν ἐν τῶι κόσμωι γινομένων.",
  "[25] Maxim. Tyr. XII 4 p. 489 [ nach B 60. 62] ζῆι πῦρ τὸν γῆς θάνατον καὶ ἀὴρ ζῆι τὸν πυρὸς θάνατον, ὕδωρ ζῆι τὸν ἀέρος θάνατον, γῆ τὸν ὕδατος.",
  "Plut. de E 18. 392 c πυρὸς θάνατος ἀέρι γένεσις, καὶ ἀέρος θάνατος ὕδατι γένεσις.",
  "(Vgl. de primo frig.",
  "10. 949 a).",
  "Marc. IV 46 ( vor B 71) ὅτι γῆς θάνατος ὕδωρ γενέσθαι καὶ ὕδατος θάνατος ἀέρα γενέσθαι καὶ ἀέρος πῦρ καὶ ἔμπαλιν.",
  "[72] Numen. fr. 35 Thedinga bei Porphyr. antr. nymph. 10 ὅθεν καὶ Ἡράκλειτον ψυχῆισι φάναι τέρψιν ἢ θάνατον ὑγρῆισι γενέσθαι.",
  "τέρψιν δὲ εἶναι αὐταῖς τὴν εἰς γένεσιν πτῶσιν, ἀλλαχοῦ δὲ φάναι ζῆν ἡμᾶς τὸν ἐκείνων θάνατον καὶ ζῆν ἐκείνας τὸν ἡμέτερον θάνατον [Β 62] .",
  "[96] Orig. c. Cels. VI 12 p. 82, 23 Koetschau [wie 79. 80 aus Celsus] ἦθος γὰρ ἀνθρώπειον μὲν οὐκ ἔχει γνώμας, θεῖον δὲ ἔχει.",
  "[97] — — [nach 78] ἀνὴρ νήπιος ἤκουσε πρὸς δαίμονος ὅκωσπερ παῖς πρὸς ἀνδρός.",
  "[62] Orig. c. Cels. VI 42 (II 111, 11 Koetschan) εἰδέναι δὲ χρὴ τὸν πόλεμον ἐόντα ξυνόν, καὶ δίκην ἔριν, καὶ γινόμενα πάντα κατ’ ἔριν καὶ †χρεώμενα.",
  "[vgl. 138] Philodem. Rhet. I c. 57. 62 S. 351. 354 Sudh. [aus d.",
  "Stoiker Diogenes] ἡ δὲ τῶν ῥητόρων εἰσαγωγὴ πάντα τὰ θεωρήματα πρὸς τοῦτ’ ἔχει τείνοντα καὶ κατὰ τὸν Ἡράκλειτον κοπίδων ἐστὶν ἀρχηγός.",
  "[99] Plato Hipp. maior. 289 a πιθήκων ὁ κάλλιστος αἰσχρὸς ἀνθρώπων γένει συμβάλλειν.",
  "[98] — — B ἀνθρώπων ὁ σοφώτατος πρὸς θεὸν πίθηκος φανεῖται καὶ σοφίαι καὶ κάλλει καὶ τοῖς ἄλλοις πᾶσιν.",
  "[83. 82] Plotin. Enn. IV 8, 1 μεταβάλλον ἀναπαύεται καὶ κάματός ἐστι τοῖς αὐτοῖς μοχθεῖν καὶ ἄρχεσθαι.",
  "[105] Plut. Coriol 22 θυμῶι μάχεσθαι χαλεπόν·",
  "ὅ τι γὰρ ἂν θέληι, ψυχῆς ὠνεῖται.",
  "[116] — — 38 ἀλλὰ τῶν μὲν θείων τὰ πολλά, καθ’ Ἡράκλειτον, ἀπιστίηι διαφυγγάνει μὴ γιγνώσκεσθαι.",
  "[117] — de aud.",
  "7 p. 41 A βλὰξ ἄνθρωπος ἐπὶ παντὶ λόγωι ἐπτοῆσθαι φιλεῖ.",
  "[78] — cons. ad Apoll.",
  "10 p. 106 E ταὐτό τ’ ἔνι ζῶν καὶ τεθνηκὸς καὶ τὸ ἐγρηγορὸς καὶ τὸ καθεῦδον καὶ νέον καὶ γηραιόν·",
  "τάδε γὰρ μεταπεσόντα ἐκεῖνά ἐστι κἀκεῖνα πάλιν μεταπεσόντα ταῦτα.",
  "[Vgl. Sext. P.",
  "H. III 230].",
  "[95] — de superst.",
  "3 p. 166 c ὁ Ἡ.",
  "φησι τοῖς ἐγρηγορόσιν ἕνα καὶ κοινόν κόσμον εἶναι, τῶν δὲ κοιμωμένων ἕκαστον εἰς ἴδιον ἀποστρέφεσθαι.",
  "[22] — de E 8 p. 388 e πυρός τε ἀνταμοιβὴ τὰ πάντα καὶ πῦρ ἁπάντων ὅκωσπερ χρυσοῦ χρήματα καὶ χρημάτων χρυσός.",
  "[41. 40] Plut. de E 18 p. 392b ποταμῶι γὰρ οὐκ ἔστιν ἐμβῆναι δὶς τῶι αὐτῶι καθ’ Ἡράκλειτον [vgl. Β 12] οὐδὲ θνητῆς οὐσίας δὶς ἅψασθαι κατὰ ἕξιν 〈τῆς αὐτῆς〉·",
  "ἀλλ’ ὀξύτητι καὶ τάχει μεταβολῆς σκίδνησι καὶ πάλιν συνάγει (μᾶλλον δὲ οὐδὲ πάλιν οὐδ’ ὕστερον, ἀλλ’ ἅμα συνίσταται καὶ ἀπολείπει) καὶ πρόσεισι καὶ ἄπεισι.",
  "[12] — de Pyth.",
  "or. 6 p. 397 a Σίβυλλα δὲ μαινομένωι στόματι καθ’ Ἡράκλειτον ἀγέλαστα καὶ ἀκαλλώπιστα καὶ ἀμύριστα φθεγγομένη χιλίων ἐτῶν ἐξικνεῖται τῆι φωνῆι διὰ τὸν θεόν.",
  "[11] — — 18 p. 404d ὁ ἄναξ, οὗ τὸ μαντεῖόν ἐστι τὸ ἐν Δελφοῖς, οὔτε λέγει οὔτε κρύπτει ἀλλὰ σημαίνει.",
  "[29] — de exil.",
  "11 p. 604 a ἥλιος γὰρ οὐχ ὑπερβήσεται μέτρα·",
  "εἰ δὲ μή, Ἐρινύες μιν Δίκης ἐπίκουροι ἐξευρήσουσιν.",
  "[108] Plut. Sympos. III pr.",
  "1 p. 644 F ἀμαθίην γὰρ ἄμεινον κρύπτειν, ἔργον δὲ ἐν ἀνέσει καὶ παρ’ οἶνον [vgl. B 109] .",
  "[85] — — IV 4, 3. p. 669 A νέκυες γὰρ κοπρίων ἐκβλητότεροι.",
  "[115] — an seni resp. 7. p. 787 C κύνες γὰρ καταβαΰζουσιν ὧν ἂν μὴ γινώσκωσι.",
  "[38] — fac. lun. 28 p. 943 E αἱ ψυχαὶ ὀσμῶνται καθ’ Ἅιδην.",
  "[31] — aqu.",
  "et ign. comp. 7 p. 957 A; de fort.",
  "3. p. 98 C εἰ μὴ ἥλιος ἦν, ἕνεκα τῶν ἄλλων ἄστρων εὐφρόνη ἂν ἦν.",
  "[34] — Qu.",
  "Plat. 8, 4 p. 1007 D …",
  "περιόδους·",
  "ὦν ὁ ἥλιος ἐπιστάτης ὢν καὶ σκοπὸς ὁρίζειν καὶ βραβεύειν καὶ ἀναδεικνύναι καὶ ἀναφαίνειν μεταβολὰς καὶ ὥρας αἳ πάντα φέρουσι καθ’ Ἡράκλειτον κτλ. [80] — adv. Colot.",
  "20. 1118 C ἐδιζησάμην ἐμεωυτόν.",
  "[15] Polyb. XII 27 δυεῖν γὰρ ὄντων κατὰ φύσιν ὡσανεί τινων ὀργάνων ἡμῖν, οἶς πάντα πυνθανόμεθα καὶ πολυπραγμονοῦμεν, ἀκοῆς καὶ ὁράσεως, ἀληθινωτέρας δ’ οὔσης οὐ μικρῶι τῆς ὁράσεως κατὰ τὸν Ἡράκλειτον·",
  "ὀφθαλμοὶ γὰρ τῶν ὤτων ἀκριβέστεροι μάρτυρες.",
  "[61] Porphyr. zu Δ 4 [I 69, 6 Schr.] τῶι μὲν θεῶι καλὰ πάντα καὶ ἀγαθὰ καὶ δίκαια, ἄνθρωποι δὲ ἃ μὲν ἄδικα ὑπειλήφασιν ἃ δὲ δίκαια.",
  "[70] — zu Ξ 200 [I 190 Schr.] ξυνὸν γὰρ ἀρχὴ καὶ πέρας ἐπὶ κύκλου περιφερείας.",
  "[111a] Procl. in Alc. I p. 525, 21 (1864) τίς γὰρ αὐτῶν νόος ἢ φρήν; δήμων ἀοιδοῖσι πείθονται καὶ διδασκάλωι χρείωνται ὁμίλωι οὐκ εἰδότες ὅτι οἱ πολλοὶ κακοί, ὀλίγοι δὲ ἀγαθοί [vgl. Bias c. 73 a 3 ς] .",
  "[119 Anm.] Schol. Hom. AT zu Σ 251 Ἡ.",
  "ἐντεῦθεν ἀστρολόγον φησὶ τὸν Ὅμηρον καὶ ἐν οἶς φησι μοῖραν δ’ οὔ τινά φημι πεφυγμένον ἔμμεναι ἀνδρῶν’ κτλ. [120] Seneca ep. 12, 7 unus dies par omni est.",
  "[4] Sext. Emp. VII 126 κακοὶ μάρτυρες ἀνθρώποισιν ὀφθαλμοὶ καὶ ὦτα βαρβάρους ψυχὰς ἐχόντων [vgl. A 16 S. 74, 36ff.; B 101 a] .",
  "[18] Stob. flor. I 174 Hense Ἡρακλείτου.",
  "ὁκόσων λόγους ἤκουσα, οὐδεὶς ἀφικνεῖται ἐς τοῦτο, ὥστε γινώσκειν ὅτι σοφόν ἐστι πάντων κεχωρισμένον.",
  "[108] — — 175 κρύπτειν ἀμαθίην κρέσσον ἢ ἐς τὸ μέσον φέρειν [vgl. B 95] .",
  "[104a] — — 176 ἀνθρώποις γίνεσθαι ὁκόσα θέλουσιν οὐκ ἄμεινον [vgl. B 85] .",
  "[104b] — — 177 νοῦσος ὑγιείην ἐποίησεν ἡδύ, κακὸν ἀγαθόν, λιμὸς κόρον, κάματος ἀνάπαυσιν.",
  "[107] — — 178 τὸ φρονεῖν ἀρετὴ μεγίστη, καὶ σοφίη ἀληθέα λέγειν καὶ ποιεῖν κατὰ φύσιν ἐπαΐοντας.",
  "[91] — — 179 ξυνόν ἐστι πᾶσι τὸ φρονέειν.",
  "[91b] — — 179 ξὺν νόωι λέγοντας ἰσχυρίζεσθαι χρὴ τῶι ξυνῶι πάντων, ὅκωσπερ νόμωι πόλις, καὶ πολὺ ἰσχυροτέρως.",
  "τρέφονται γὰρ πάντες οἱ ἀνθρώπειοι νόμοι ὑπὸ ἑνὸς τοῦ θείου·",
  "κρατεῖ γὰρ τοσοῦτον ὁκόσον ἐθέλει καὶ ἐξαρκεῖ πᾶσι καὶ περιγίνεται.",
  "[0] Stob. flor. I 180a ψυχῆς ἐστι λόγος ἑαυτὸν αὔξων.",
  "[106] — — v 6 ἀνθρώποισι πᾶσι μέτεστι γινώσκειν ἑωυτοὺς καὶ φρονεῖν.",
  "[73] — — 7 ἀνὴρ ὁκόταν μεθυσθῆι, ἄγεται ὑπὸ παιδὸς ἀνήβου σφαλλόμενος, οὐκ ἐπαΐων ὅκη βαίνει, ὑγρὴν τὴν ψυχὴν ἔχων.",
  "[74—76] — — 8 αὐγὴ ξηρὴ ψυχὴ σοφωτάτη καὶ ἀρίστη [121] — — IV 40, 23 Ἡ.",
  "ἔφη ὡς ἦθος ἀνθρώπωι δαίμων.",
  "[30] Strabo I 6 p. 3 Βέλτιον δ’ Ἡ.",
  "καὶ ὁμηρικωτέρως ὁμοίως ἀντὶ τοῦ ἀρκτικοῦ τὴν ἄρκτον ὀνομάζων·",
  "ἠοῦς καὶ ἑσπέρας τέρματα ἡ ἄρκτος καὶ ἀντίον τῆς ἄρκτου οὖρος αἰθρίου Διός.",
  "ὁ γὰρ ἀρκτικός ἐστι δύσεως καὶ ἀνατολῆς ὅρος, οὐχ ἡ ἄρκτος.",
  "[114] XIV 25 p. 642. Diog. IX 2 [s. S. 67, 29] ἄξιον Ἐφεσίοις ἡβηδὸν ἀνάγξασθαι πᾶσι καὶ τοῖς ἀνήβοις τὴν πόλιν καταλιπεῖν, οἵτινες Ἑρμόδωρον ἄνδρα ἑωυτῶν ὀνήιστον ἐξέβαλον φάντες·",
  "ἡμέων μηδὲ εἶς ὀνήιστος ἔστω, εἰ δὲ μή, ἄλλη τε καὶ μετ’ ἄλλων.",
  "[9] Suid. s. v. ἀμφισβατεῖν und ἀγχιβατεῖν: ἀγχιβασίην Ἡράκλειτος.",
  "[10] Themist. or. 5 p. 69 φύσις δὲ καθ’ Ἡράκλειτον κρύπτεσθαι φιλεῖ.",
  "[46 Anm.] Theophr. Metaphys. 15 p. 7a 10 Usen. ἄλογον δὲ κἀκεῖνο δόξειεν ἄν, εἰ ὁ μὲν ὅλος οὐρανὸς καὶ ἕκαστα τῶν μερῶν ἅπαντ’ ἐν τάξει καὶ λόγωι, καὶ μορφαῖς καὶ δυνάμεσιν καὶ περιόδοις, ἐν δὲ ταῖς ἀρχαῖς μηθὲν τοιοῦτον, ἀλλ’ ὥσπερ σάρμα εἰκῇ κεχυμένον ὁ κάλλιστος, φησὶν Ἡράκλειτος, [ὁ] κόσμος.",
  "[84] Theophr. de vert.",
  "9 καὶ ὁ κυκεὼν διίσταται 〈μὴ〉 κινούμενος.",
  "[0] Tzetzes ad Aristoph. Plut. 88 [Ambr., Paris.] τυφλὸν δὲ τὸν Πλοῦτον ποιεῖ ὡς οὐκ ἀρετῆς, κακίας δὲ παραιτίου.",
  "ὅθεν καὶ Ἡ.",
  "ὁ Ἐφέσιος ἀρώμενος Ἐφεσίοις, οὐκ ἐπευχόμενος·",
  "μὴ ἐπιλίποι ὑμᾶς πλοῦτος, ἔφη, Ἐφέσιοι, ἵν’ ἐξελέγχοισθε πονηρευόμενοι.",
  "[39] schol.",
  "ad exeg.",
  "II p. 126 Herm. τὰ ψυχρὰ θέρεται, θερμὸν ψύχεται, ὑγρὸν αὐαίνεται, καρφαλέον νοτίζεται.",
  "[0] Anatol.",
  "de decade p.36 Heiberg (Annales d’histoire.",
  "Congrès de Paris 1901. 5. section) κατὰ λόγον δὲ ὡρέων συμβάλλεται ἑβδομὰς κατὰ σελήνην, διαιρεῖται δὲ κατὰ τὰς ἄρκτους, ἀθανάτου Μνήμης σημείω.",
  "[0] Anonym. in Plat. Τheaet.",
  "[Berl.",
  "Klassikert.",
  "2] 71, 12 zu p. 152 E [13 A 6] Ἐπίχαρμος ὁ 〈ὁμιλή〉σας τοῖς Πυθα〈γορείοις〉 ἄλλα τ〈έ〉 τινα ἐ〈πινενόη〉κεν δ〈ειν〉ὰ τ〈όν τε περὶ το〉ῦ αὐξο〈μένου λόγον〉.",
  "ἐφοδ〈εύει δὲ κατὰ τὸ〉 Ἡρα〈κλείτου〉 ἄλλως ἄ〈λλο ἀεὶ αὔξε〉ται πρὸς ὃ 〈ἂν ἦι ἐλλι〉πές .",
  "εἰ οὖν 〈μηδεὶς〉 〈παύε〉ται 〈ρέων καὶ ἀλ〉λ〈ἀτ〉των 〈τὸ εἶδος, αἱ〉 οὐσίαι ἄλλ〈οτε ἄλλαι〉 γίνονται 〈κατὰ συν〉εχῆ ῥύσιν.",
  "[0] Aristocritus Theos. 69 [ nach B 5] ὁ αὐτὸς πρὸς Αἰγυπτίους ἔφη·",
  "εἰ θεοί εἰσιν, ἵνα τί θρηνεῖτε αὐτούς; εἰ δὲ θρηνεῖτε αὐτούς, μηκέτι τούτους ἡγεῖσθε θεούς.",
  "[0] — 74 ὅτι ὁ Ἡράκλειτος ὁρῶν τοὺς Ἕλληνας γέρα τοῖς δαίμοσιν ἀπονέμοντας εἶπεν·",
  "δαιμόνων ἀγάλμασιν εὔχονται οὐκ ἀκούουσιν, ὥσπερ ἀκούοιεν, οὐκ ἀποδιδοῦσιν, ὥσπερ οὐκ ἀπαιτοῖεν.",
  "[17] Diog. VIII 6 Πυθαγόρης Μνησάρχου ἱστορίην ἤσκησεν ἀνθρώπων μάλιστα πάντων καὶ ἐκλεξάμενος ταύτας τὰς συγ γραφὰς ἐποιήσατο ἑαυτοῦ σοφίην, πολυμαθείην, κακοτε χνίην.",
  "[0] Gnomol. Monac. lat. I 19 (Caecil. Balb. Wölffin p. 18) non convenit ridiculum esse ita, ut ridiculus ipse videaris. Heraclitus dixit.",
  "[134] Paris. ed. Sternbach n. 209 ὁ δὲ γε Ἡ.",
  "ἔλεγε τὴν οἴησιν κροκοκῆς ἐγκοπήν.",
  "[0] — Vatic. 743 n. 312 Sternb.",
  "τιμαὶ θεοὺς καὶ ἀνθρώπους καταδουλοῦνται.",
  "[0] —— 313 ἄνθρωποι κακοὶ ἀληθινῶν ἀντίδικοι.",
  "[135] —— 314 τὴν παιδείαν ἕτερον ἥλιον εἶναι τοῖς πεπαιδευμἐνοις.",
  "[137] —— 315 συντομωτάτην ὁδὸν ἔλεγεν εἰς εὐδοξίαν τὸ γενέσθαι ἀγαθόν.",
  "[0] Schol. Epictet.",
  "Bodl. p. LXXI Schenkl Ἡρακλείτου·",
  "ψυχαὶ ἀρηίφατοι καθερώτεραι (20) ἢ ἐνὶ νούσοις.",
  "[63] Stob. ecl. I 5, 15 p.78, 11 ( nach Aët. I 27, 1 S. 12 A 8) γράφει γοῦν ἔστι γὰρ εἱμαρμένα πάντως …",
  "[0] Cod. Paris. 1630 s. XIV f. 191r Ἡρακλείτου φιλοσόφου κατὰ τοῦ βίου.",
  "81 Ποίην τίς βιότοιο τάμοι τρίβον κτλ. = Anth. Pal. IX 359. Stob. fl. 98, 57 = Posidipp. ep. 21 p. 79 Schott. [0] Catal. Codd. Astrol. Graec. IV 38 VII 106 Ἡρακλείτου φιλοσόφου.",
  "Ἐπειδὴ φασί τινες εἰς ἀρχὰς κεῖσθαι τὰ ἄστρα …",
  "μέχρις οὑ ἐθέλει ὁ ποιήσας αὐτόν."
],

palabras: [
  "montaña","monte","cordillera","risco","ladera","cumbre","valle","cañada","barranco",
  "río","arroyo","torrente","laguna","estanque","mar","vado","orilla","cascada","manantial",
  "nube","niebla","bruma","viento","brisa","lluvia","nieve","escarcha","rocío","tormenta",
  "sol","luna","astro","estrella","aurora","ocaso","cielo","bóveda","horizonte","sombra",
  "pino","bambú","sauce","musgo","yerba","loto","junco","raíz","hoja","semilla",
  "helecho","hongo","liquen","alga","espora","coral","medusa","zarza","enredadera","micelio",
  "pez","ave","pájaro","mono","grulla","garza","ciervo","cangrejo","pescador","recluso",
  "polilla","luciernaga","abeja","perro","rata","caracol","gusano","larva","bacteria","tentáculo",
  "piedra","roca","arena","polvo","jade","sal","fuego","brasa","ceniza","humo",
  "basalto","cuarzo","obsidiana","arcilla","barro","hielo","mineral","meteorito","cristal","óxido",
  "silencio","vacío","quietud","distancia","camino","sendero","umbral","confín","territorio","topología",
  "isla","islote","meseta","altiplano","duna","delta","estuario","glaciar","costa","frontera",
  "jardín","invernadero","caverna","templo","choza","puente","muelle","taberna","ermita","santuario"
],

palabras_interplanetarias: [
  "órbita","astrofaro","nave","cápsula","módulo","estación","colonia","cúpula","hábitat","biosfera",
  "terraformación","exoplaneta","asteroide","cometa","cráter","regolito","anillo","satélite","sonda","antena",
  "propulsor","reactor","motor","turbina","vela solar","esclusa","cabina","visor","traje","casco",
  "gravedad","microgravedad","vacío","radiación","plasma","nebulosa","púlsar","cuásar","supernova","horizonte de sucesos",
  "cinturón de Oort","heliopausa","magnetosfera","ionosfera","atmósfera","exilio orbital","ruta estelar","puerto lunar","jardín marciano","archivo terrestre",
  "semilla criogénica","arca botánica","museo de océanos","mapa de constelaciones","cementerio orbital","monasterio espacial","río de fotones","mar de metano","lluvia de polvo","amanecer doble"
],

palabras_soledad_y_nostalgia: [
  "exilio","añoranza","desarraigo","retorno","hogar","patria","origen","duelo","memoria","ausencia",
  "distancia","separación","abandono","eco","recuerdo","infancia","llanto","cansancio","vigilia","espera",
  "último habitante","última carta","última lluvia","última playa","último bosque","última taberna","última cosecha","última ventana","última canción","último idioma",
  "tierra natal","casa perdida","olor de lluvia","barro de infancia","perro viejo","mercado remoto","río familiar","jardín materno","sombra del sauce","montaña recordada",
  "soledad mineral","soledad humana","soledad terrestre","soledad orbital","soledad de reactor","soledad de invernadero","soledad de casco","soledad de luna","soledad de señal","soledad de archivo"
],

palabras_maquina_divina: [
  "máquina divina","deus machina","altar hidráulico","querubín mecánico","ángel de fibra óptica","serafín industrial","motor sagrado","turbina litúrgica","reactor votivo","engranaje celeste",
  "catedral de datos","santuario orbital","incensario eléctrico","campana neumática","relicario de silicio","hostia de luz","oráculo computacional","profeta algorítmico","monje robot","sacerdote de cobre",
  "liturgia de sensores","salmo binario","sutra de código","plegaria magnética","evangelio de circuitos","apocalipsis suave","juicio de las máquinas","resurrección vegetal","compost sagrado","cripta de semillas",
  "reloj cósmico","mandala mecánico","rueda de cálculo","corazón de reactor","ojo de cámara","iris artificial","pupila de vidrio","aureola holográfica","corona de antenas","halo de plasma"
],

palabras_escatologicas_exotericas: [
  "fin del mundo","último día","último sol","cielo abierto","tierra quemada","mar retirado","ciudad vacía","tumba estelar","arca final","semilla posterior",
  "resurrección","juicio","profecía","presagio","revelación","catástrofe","ruina","cenotafio","osario","reliquia",
  "procesión pública","culto visible","rito exterior","templo abierto","símbolo expuesto","sagrado turístico","misterio iluminado","doctrina visible","icono popular","milagro transmitido",
  "trompeta oxidada","lluvia de ceniza","luz de extinción","corona funeraria","santo de neón","peregrino orbital","evangelio de polvo","apóstol de silicio","sacramento de agua reciclada","paraíso botánico"
],

palabras_haraway_wolfram_galloway_wark: [
  "simpoiesis","compost","parentesco multiespecie","criaturas compañeras","responsabilidad compartida","tentacularidad","holobioma","resurgimiento","biología salvaje","mundo dañado",
  "regla simple","autómata celular","irreductibilidad computacional","universo computacional","emergencia","complejidad","grafo multiway","ruliología","patrón irreducible","cálculo natural",
  "interfaz","intrafaz","efecto de interfaz","umbral","pantalla","ventana","puerta","Iris","Hermes","Furias",
  "iridiscencia","iluminación","mensaje","red","enjambre","mediación","excomunicación","hipercomunicación","brillo afectivo","lumen terrestre",
  "abstracción","clase hacker","vector","información","propiedad","commodity","hack","mundo nuevo","diferencia","trabajo abstracto",
  "capital de ciencia ficción","contrafuturo","arqueología futura","memoria rota","archivo colonial","cronopolítica","futuro confiscado","señal diaspórica","countermemory","ruina especulativa"
],

verbos_para_prompts: [
  "orbitar","flotar","germinar","recircular","terraformar","recordar","desvanecer","condensar","transmitir","codificar",
  "hackear","abstraer","ensamblar","componer","descomponer","fermentar","compostar","resurgir","mutar","devenir",
  "iluminar","mediar","interfazar","enjambrar","difractar","refractar","irisarse","plegar","desplegar","estratificar",
  "desterritorializar","reterritorializar","modular","filtrar","recitar","rezar","calcular","simular","archivar","invocar",
  "navegar","remar","peregrinar","cruzar","ascender","descender","contemplar","callar","escuchar","beber",
  "arder","enfriar","nevar","brotar","llover","erosionar","fosilizar","cristalizar","evaporar","cantar"
],

adjetivos_y_texturas: [
  "verde profundo","azul remoto","blanco escarchado","dorado orbital","gris mineral","negro cósmico","rojo marciano","violeta litúrgico","plateado lunar","jade translúcido",
  "iridiscente","holográfico","tentacular","micelial","compostado","estratificado","fracturado","difractado","anamórfico","xenomórfico",
  "sagrado","exotérico","escatológico","monástico","mecánico","botánico","hidráulico","neumático","algorítmico","arcaico",
  "terrestre","postterrestre","interplanetario","orbital","criogénico","radiante","oxidado","silencioso","húmedo","polvoriento",
  "melancólico","contemplativo","errante","ancestral","inhumano","multiespecie","computacional","irreductible","luminoso","fantasmal"
],

motivos_visuales: [
  "choza de paja dentro de una cúpula espacial",
  "pinos creciendo junto a un reactor sagrado",
  "bambú iluminado por Saturno",
  "lotos flotando en agua cometaria",
  "monje robot barriendo polvo lunar",
  "pescador solitario en un río de Europa",
  "jardín terrestre dentro de una nave antigua",
  "Tierra azul vista desde una taberna orbital",
  "altar de engranajes cubierto de musgo",
  "querubines de fibra óptica reparando un invernadero",
  "Iris artificial abriendo un arco iris dentro de una pantalla",
  "Hermes como dron mensajero sobre montañas verdes",
  "Furias como enjambre de sensores en una ciudad vacía",
  "autómatas celulares creciendo como helechos",
  "reglas simples formando nubes, ríos y rostros",
  "archivo botánico de especies extintas",
  "cementerio orbital con flores impresas",
  "mapa de la Tierra bordado en una manta térmica",
  "niño nacido en Marte dibujando lluvia",
  "anciano contemplando una montaña simulada",
  "museo de océanos dentro de un asteroide",
  "semillas criogénicas como reliquias religiosas",
  "jazz interestelar en una cúpula de bambú",
  "saxofón bajo auroras artificiales",
  "interfaces rotas mostrando paisajes de infancia",
  "pantallas cubiertas de líquenes",
  "código escrito como sutra sobre papel de arroz",
  "río Amarillo convertido en constelación",
  "choza taoísta orbitando un planeta sin nombre",
  "última lluvia reproducida por altavoces en una colonia"
],

sintagmas_para_mezclar: [
  "la nostalgia del barro natal",
  "el zumbido del templo mecánico",
  "la pupila iridiscente de la interfaz",
  "la soledad mineral del cosmos",
  "el compost de los muertos futuros",
  "la arca botánica de la última Tierra",
  "la montaña comprimida en memoria",
  "el río de datos bajo la choza",
  "la plegaria de los ventiladores",
  "el halo de plasma del monje robot",
  "la última semilla del mercado terrestre",
  "la lluvia archivada en un sensor",
  "el jardín que desobedece al plano",
  "la regla simple que sueña bosques",
  "el algoritmo que aprende a llorar",
  "el reactor cubierto de líquenes",
  "la aurora que no consuela",
  "la taza flotando en microgravedad",
  "el pino que canta sin viento",
  "la catedral de agua reciclada",
  "la brújula rota de los exiliados",
  "la niebla del planeta ajeno",
  "el ojo de vidrio de Iris",
  "el mensaje perdido de Hermes",
  "el enjambre judicial de las Furias",
  "la abstracción que cruza el valle",
  "el hacker que libera una montaña",
  "el santo de neón en la esclusa",
  "el pez soñando océanos extintos",
  "la Tierra como fruta azul distante"
],
  /* ---- el sub-verbo: conjuntos de caracteres abstractos ---- */
  glifos: {

    /* sextantes — Symbols for Legacy Computing, la trama de sutileza */
    sextantes: ["🬀","🬁","🬂","🬃","🬄","🬅","🬆","🬇","🬈","🬉","🬊","🬋","🬌","🬍","🬎","🬏","🬐","🬑","🬒","🬓","🬔","🬕","🬖","🬗","🬘","🬙","🬚","🬛","🬜","🬝","🬞","🬟","🬠","🬡","🬢","🬣","🬤","🬥","🬦","🬧","🬨","🬩","🬪","🬫","🬬","🬭","🬮","🬯","🬰","🬱","🬲","🬳","🬴","🬵","🬶","🬷","🬸","🬹","🬺","🬻"],

    /* cuñas y diagonales — laderas */
    cunas: ["🬼","🬽","🬾","🬿","🭀","🭁","🭂","🭃","🭄","🭅","🭆","🭇","🭈","🭉","🭊","🭋","🭌","🭍","🭎","🭏","🭐","🭑","🭒","🭓","🭔","🭕","🭖","🭗","🭘","🭙","🭚","🭛","🭜","🭝","🭞","🭟","🭠","🭡"],

    /* legacy computing — sombras, filos, marcos */
    legacy: ["🭰","🭱","🭲","🭳","🭴","🭵","🭶","🭷","🭸","🭹","🭺","🭻","🭼","🭽","🭾","🭿","🮀","🮁","🮂","🮃","🮄","🮅","🮆","🮇","🮈","🮉","🮊","🮋","🮌","🮍","🮎","🮏","🮐","🮑","🮒","🮔","🮕","🮖","🮗","🮘","🮙","🮚","🮛","🮜","🮝","🮞","🮟"],

    /* block elements — el macizo */
    bloques: ["▀","▁","▂","▃","▄","▅","▆","▇","█","▉","▊","▋","▌","▍","▎","▏","▐","░","▒","▓","▔","▕","▖","▗","▘","▙","▚","▛","▜","▝","▞","▟"],

    /* box drawing — las cajas, los circuitos */
    cajas: ["─","━","│","┃","┄","┅","┆","┇","┈","┉","┊","┋","┌","┍","┎","┏","┐","┑","┒","┓","└","┕","┖","┗","┘","┙","┚","┛","├","┝","┞","┟","┠","┡","┢","┣","┤","┥","┦","┧","┨","┩","┪","┫","┬","┭","┮","┯","┰","┱","┲","┳","┴","┵","┶","┷","┸","┹","┺","┻","┼","┽","┾","┿","╀","╁","╂","╃","╄","╅","╆","╇","╈","╉","╊","╋","═","║","╒","╓","╔","╕","╖","╗","╘","╙","╚","╛","╜","╝","╞","╟","╠","╡","╢","╣","╤","╥","╦","╧","╨","╩","╪","╫","╬","╭","╮","╯","╰","╱","╲","╳"],

    /* disco de festos — la voz muerta, indescifrada */
    phaistos: ["𐇐","𐇑","𐇒","𐇓","𐇔","𐇕","𐇖","𐇗","𐇘","𐇙","𐇚","𐇛","𐇜","𐇝","𐇞","𐇟","𐇠","𐇡","𐇢","𐇣","𐇤","𐇥","𐇦","𐇧","𐇨","𐇩","𐇪","𐇫","𐇬","𐇭","𐇮","𐇯","𐇰","𐇱","𐇲","𐇳","𐇴","𐇵","𐇶","𐇷","𐇸","𐇹","𐇺","𐇻","𐇼"],

    /* tibetano — la escritura ornamento */
    tibetano: ["ༀ","༁","༂","༃","༄","༅","༆","༇","༈","༉","༊","࿄","࿅","࿊","࿋","࿌","༐","༑","༒","༓","༔","༕","༖","༗","࿎","࿏","༝","༞","༟","༴","࿇","࿈","࿉"],

    /* ogham — el trazo vertical, la muesca */
    ogham: ["ᚁ","ᚂ","ᚃ","ᚄ","ᚅ","ᚆ","ᚇ","ᚈ","ᚉ","ᚊ","ᚋ","ᚌ","ᚍ","ᚎ","ᚏ","ᚐ","ᚑ","ᚒ","ᚓ","ᚔ","ᚕ","ᚖ","ᚗ","ᚘ","ᚙ","ᚚ","᚛","᚜"],

    /* runas — el signo tallado */
    runas: ["ᚠ","ᚡ","ᚢ","ᚣ","ᚤ","ᚥ","ᚦ","ᚧ","ᚨ","ᚩ","ᚪ","ᚫ","ᚬ","ᚭ","ᚮ","ᚯ","ᚰ","ᚱ","ᚲ","ᚳ","ᚴ","ᚵ","ᚶ","ᚷ","ᚸ","ᚹ","ᚺ","ᚻ","ᚼ","ᚽ","ᚾ","ᚿ","ᛀ","ᛁ","ᛂ","ᛃ","ᛄ","ᛅ","ᛆ","ᛇ","ᛈ","ᛉ","ᛊ","ᛋ","ᛌ","ᛍ","ᛎ","ᛏ","ᛐ","ᛑ","ᛒ","ᛓ","ᛔ","ᛕ","ᛖ","ᛗ","ᛘ","ᛙ","ᛚ","ᛛ","ᛜ","ᛝ","ᛞ","ᛟ","ᛠ","ᛡ","ᛢ","ᛣ","ᛤ","ᛥ","ᛦ","ᛧ","ᛨ","ᛩ","ᛪ"],

    /* geometrias imposibles — el volumen plano, el diagrama */
    geometrias: ["◈","◇","◆","◉","○","●","◐","◑","◒","◓","◔","◕","◖","◗","⬡","⬢","⬣","⬟","⬠","⏢","⏥","⌬","⌭","⌮","⏣","⟁","⟐","⟡","⟢","⟣","⧉","⧠","⧨","⧩","⧪","⧫","⬢","▰","▱","◧","◨","◩","◪","⚟","⚠"],

    /* marcas — registro, mira, plano */
    marcas: ["⌖","⊹","✛","✜","✚","✢","✣","✤","⁙","⁘","⌗","⏚","⏛","⎔","⟟","⟠","⌌","⌍","⌎","⌏","⌐","¬","⌜","⌝","⌞","⌟","⊹","⋆","✦","✧","⟊","⟒","⏦","⏧","⌁","⌇","∴","∵","※","⁂"],

    /* ondas — el agua, la señal */
    ondas: ["∿","≈","≋","﹏","〰","⌇","≀","~","･","∼","≃","≅","⋿","⌁","⍨","⍩"],

    /* matematicas abstractas — el operador desnudo */
    operadores: ["⨀","⨁","⨂","⨃","⨄","⨅","⨆","⨇","⨈","⨉","⨊","⨋","∮","∯","∰","∇","∆","∂","∏","∐","∑","√","∛","∜","∝","∞","⊕","⊗","⊙","⊘","⊚","⊛","⊜","⊝","⋀","⋁","⋂","⋃","⌀","⍟","⍉","⊹"]
  },

  /* ---- la jerga del plano ---- */
  tecnica: {
    siglas: ["VENT","SEC","TERR","NODE","GRID","REF","VEC","SRC","DST","ORG","SYS","MAP",
             "TOPO","LINK","FLUX","SIG","CTRL","BUS","LAT","LON","ALT","AZ","IDX","REV",
             "CAL","RAW","BIT","DAT","OBS","SPAN","ZONE","AREA","EDGE","MESH","FIELD","LAB"],
    unidades: ["dB","‰","°","′","″","µ","∆","λ","θ","φ","Ω","Ø","Hz","px","km","m","‱","%","§","№"],
    signos: ["//","／／","::","··","⟨⟩","[ ]","{ }","⟦⟧","⌈⌉","⌊⌋","→","↦","⇢","⇥","↳","⤳","⊢","⊣","⊤","⊥","∷","≔","≝","≟"]
  }
};

if (typeof module !== 'undefined') module.exports = VOC;
