const PALETTES=[['#f4ff00','#130044','#ff2a00','#0057ff','#00e6a8'],['#ff5fd1','#071a12','#ffeb00','#5a00ff','#00ff9d'],['#0717ff','#fff7df','#ff3b00','#00eaff','#d7ff00'],['#ff6b00','#13002d','#ffea00','#2e00ff','#00ffc8'],['#0a0a0a','#f8f1dd','#ff2851','#38d7ff','#d9ff00'],['#e7ddff','#190058','#ff003d','#008cff','#66ff00'],['#00d48b','#1f0033','#ff174f','#0055ff','#f7ff00'],['#fff6e7','#111','#ff2200','#2c36ff','#00ca7d']];
const SCENES=[['AUTÓMATA DEL MALENTENDIDO','cada letra obedece a sus ocho vecinas menos cuando se siente observada'],['GRÁFICA DE LO QUE NO ALCANZA A SER DATO','los ejes cambian de unidad para conservar la conclusión'],['COMPRESIÓN / INCOMPRESIÓN','el sentido pierde peso · el archivo aumenta de tamaño'],['RED SOCIAL PARA COSAS SIN PERFIL','ningún centro acepta los términos y condiciones'],['TORMENTA DE VENTANAS','todo afuera abre dentro de otra ventana'],['PRONÓSTICO PARA UNA MEMORIA LOCAL','posibilidad de archivo con ráfagas de olvido'],['ORÁCULO MEMÉTICO','el chiste contiene más protocolo que la explicación'],['AVALANCHA DIAGRAMÁTICA','entrada → operación → accidente → otra entrada']];
const TEXTS=['100 TABS OPEN / 0 WORLDS CLOSED','el mundo hizo click fuera del modal','NO ERA UN BUG / ERA UNA FORMA DE INTIMIDAD','la flecha llegó antes que la causa','SELECT ALL / DESELECT REALITY','mi nube tiene clima laboral','404: AFUERA NOT FOUND','el diagrama insiste en que somos amigos','loading… la metáfora se cansó','ZIP YOUR FEELINGS','esta frase ocupa más memoria cuando la entiendes','el archivo recuerda únicamente sus contraseñas incorrectas','si puede leerse en un orden / ese orden ya falló','una sonda pregunta si todavía estamos ahí','la copia envejece antes que su fuente','NODO SIN CENTRO BUSCA RELACIÓN ESTABLE','aceptar todas las cookies del desierto','la página carga / el mundo no','todo texto es un gráfico que olvidó sus ejes','ERROR 200: TODO SALIÓ DEMASIADO BIEN','el presente se repite para parecer continuo','NO HAY ORIGINAL / PERO YA LO HABÍAS PENSADO','el cursor también está siendo observado','cada lectura fabrica el documento que afirma descubrir','la escala fue despedida por no representar resultados','este poema requiere permisos de administrador','la ruina todavía tiene procesos en segundo plano','¿eres humano? selecciona todas las imágenes con mundo','ctrl + z no revierte una profecía','el gráfico sube porque le dimos palabras de ánimo','MODO AVIÓN PARA UNA SONDA ESPACIAL','la celda no está vacía / está ejecutando silencio'];
const GLYPHS='◉⊕⌖⟁◌∿▓▒░╳⌁↺⇢⟲⧉⦿✣✦☍⤬∴∵⨳⫷⫸'.split('');
const M=document.querySelector('#machine'),C=document.querySelector('#field'),X=C.getContext('2d'),swarm=document.querySelector('#swarm'),link=document.querySelector('#link');
let scene=0,loop=0,mut=0,palette=0,paused=false,tempo=10500,words=[],selected=[],frame=0,last=performance.now(),cells=[],nodes=[],bars=[],wins=[],timer;
const pointer={x:.5,y:.5,energy:0};
function hash(s){let h=1779033703^s.length;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),3432918353);return(h^(h>>>16))>>>0}
function seeded(s){let a=hash(s)||1;return()=>{a+=0x6d2b79f5;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
function makeSystem(){const r=seeded(scene+':'+mut);cells=Array.from({length:1092},()=>r()>.61?1:0);nodes=Array.from({length:28},()=>({x:r(),y:r(),vx:(r()-.5)*.002,vy:(r()-.5)*.002,s:3+r()*13}));bars=Array.from({length:21},r);wins=Array.from({length:16},()=>({x:r(),y:r(),w:.1+r()*.24,h:.08+r()*.23,v:(r()-.5)*.0025}))}
function makeWords(){const r=seeded(scene+':'+mut+':read'),n=13+Math.floor(r()*9);words=Array.from({length:n},(_,i)=>({id:i,text:TEXTS[(i*5+scene*3+mut+Math.floor(r()*TEXTS.length))%TEXTS.length],x:2+r()*88,y:10+r()*79,size:.55+Math.pow(r(),1.8)*3.8,rot:r()<.22?[-90,90,180][Math.floor(r()*3)]:-13+r()*26,mode:Math.floor(r()*5)}));renderWords()}
function renderWords(){swarm.innerHTML='';words.forEach(w=>{const b=document.createElement('button');b.className='bit mode-'+w.mode+(selected.includes(w.id)?' selected':'');b.style.cssText=`left:${w.x}%;top:${w.y}%;--s:${w.size};--r:${w.rot}deg`;b.innerHTML=`<small>${GLYPHS[(w.id+scene)%GLYPHS.length]} ${w.id.toString(16).padStart(2,'0')}</small>${w.text}`;b.onclick=()=>mutate(w.id);swarm.append(b)});renderLink()}
function mutate(id){selected=selected.includes(id)?selected.filter(x=>x!==id):[...selected.slice(-1),id];const w=words.find(x=>x.id===id);w.text=TEXTS[(TEXTS.indexOf(w.text)+7+mut)%TEXTS.length];w.x=(w.x+17+Math.random()*23)%91;w.y=8+(w.y+Math.random()*31)%80;w.rot+=Math.random()>.5?90:-90;mut++;renderWords();ui()}
function renderLink(){if(selected.length!==2){link.style.display='none';return}const a=words.find(w=>w.id===selected[0]),b=words.find(w=>w.id===selected[1]);link.style.display='block';link.querySelector('path').setAttribute('d',`M${a.x},${a.y} Q50,${15+mut%70} ${b.x},${b.y}`);link.querySelector('text').textContent=['LOL','CONTRADICE','CONTAGIA','COMPRIME','REPOSTEA'][mut%5]}
function applyPalette(){const p=PALETTES[palette];['bg','ink','hot','cold','acid'].forEach((n,i)=>M.style.setProperty('--'+n,p[i]))}
function ui(){document.querySelector('#number').textContent=String(scene+1).padStart(2,'0');document.querySelector('#title').textContent=SCENES[scene][0];document.querySelector('#subtitle').textContent=SCENES[scene][1];document.querySelector('#status').textContent=`LOOP ${String(loop+1).padStart(2,'0')} / MOTOR ${String(scene+1).padStart(2,'0')} / MUT ${String(mut).padStart(4,'0')}`;document.querySelector('#clock').textContent=paused?'TIEMPO COMPRIMIDO':`CAMBIO EN ${(tempo/1000).toFixed(1)}s`;document.querySelector('#meta').textContent=`PALETA #${palette+1} · ${selected.length}/2 NODOS · RANDOM NO ES SINÓNIMO DE INOCENTE`;document.querySelector('#ticker').textContent=TEXTS[(mut+scene*2)%TEXTS.length];document.querySelector('#pause').textContent=paused?'DESCOMPRIMIR':'COMPRIMIR';[...document.querySelectorAll('nav button')].forEach((b,i)=>b.classList.toggle('active',i===scene))}
function go(n=(scene+1)%8){if(n===0&&scene===7)loop++;scene=n;mut++;palette=Math.floor(Math.random()*8);selected=[];applyPalette();makeSystem();makeWords();ui();restart()}
function restart(){clearInterval(timer);if(!paused)timer=setInterval(()=>go(),tempo)}
function resize(){const d=Math.min(1.5,devicePixelRatio||1);C.width=innerWidth*d;C.height=innerHeight*d;C.style.width=innerWidth+'px';C.style.height=innerHeight+'px';X.setTransform(d,0,0,d,0,0)}
function line(a,b,c,d,color,w=1){X.strokeStyle=color;X.lineWidth=w;X.beginPath();X.moveTo(a,b);X.lineTo(c,d);X.stroke()}
function label(s,x,y,z,color,rot=0){X.save();X.translate(x,y);X.rotate(rot);X.fillStyle=color;X.font=`800 ${z}px monospace`;X.fillText(s,0,0);X.restore()}
function arrow(a,b,c,d,color){line(a,b,c,d,color,1.5);const q=Math.atan2(d-b,c-a);X.fillStyle=color;X.beginPath();X.moveTo(c,d);X.lineTo(c-Math.cos(q-.45)*10,d-Math.sin(q-.45)*10);X.lineTo(c-Math.cos(q+.45)*10,d-Math.sin(q+.45)*10);X.fill()}
function draw(now){const dt=Math.min(50,now-last);last=now;if(!paused)frame+=dt/16.67;pointer.energy*=.975;const w=innerWidth,h=innerHeight,t=frame/60,[bg,ink,hot,cold,acid]=PALETTES[palette];X.fillStyle=bg;X.fillRect(0,0,w,h);X.globalAlpha=.96;
 if(scene===0){const co=42,ro=26,cw=w/co,ch=h/ro;if(Math.floor(frame)%10===0&&!paused){const nx=cells.slice();for(let y=0;y<ro;y++)for(let x=0;x<co;x++){let n=0;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)if(xx||yy)n+=cells[((y+yy+ro)%ro)*co+(x+xx+co)%co];nx[y*co+x]=n===3||(cells[y*co+x]&&n===2)?1:0}cells=nx}X.font=Math.max(12,cw*.82)+'px monospace';cells.forEach((on,i)=>{if(on){X.fillStyle=[ink,hot,cold,acid][(i+Math.floor(t))%4];X.fillText(GLYPHS[(i+frame/8|0)%GLYPHS.length],i%co*cw,Math.floor(i/co)*ch)}})}
 if(scene===1){const ox=w*.08,oy=h*.78;arrow(ox,oy,w*.94,oy,ink);arrow(ox,oy,ox,h*.1,ink);bars.forEach((v,i)=>{const x=ox+i*(w*.82/21),q=v*.5+Math.sin(t*.8+i)*.2+pointer.y*.25;X.fillStyle=[hot,cold,acid][i%3];X.fillRect(x,oy,w*.82/26,-q*h*.63)});X.strokeStyle=ink;X.lineWidth=5;X.beginPath();for(let x=0;x<w;x+=8){const y=h*.45+Math.sin(x*.018+t*2)*h*.13+Math.sin(x*.061-t)*h*.04;x?X.lineTo(x,y):X.moveTo(x,y)}X.stroke();label('↑ entusiasmo del gráfico',w*.12,h*.15,18,hot)}
 if(scene===2)for(let i=0;i<62;i++){const y=i*h/61,s=.08+Math.abs(Math.sin(t*.45+i*.17+pointer.x*4))*1.2;X.save();X.translate(w/2,y);X.scale(s,1);X.fillStyle=[ink,hot,cold,acid][i%4];X.font=7+i%8*2+'px monospace';X.textAlign='center';X.fillText(TEXTS[i%TEXTS.length].repeat(i%3+1),0,0);X.restore()}
 if(scene===3)nodes.forEach((n,i)=>{if(!paused){n.x+=n.vx;n.y+=n.vy;if(n.x<0||n.x>1)n.vx*=-1;if(n.y<0||n.y>1)n.vy*=-1}nodes.slice(i+1).forEach(b=>{const d=Math.hypot(n.x-b.x,n.y-b.y);if(d<.23)line(n.x*w,n.y*h,b.x*w,b.y*h,d<.1?hot:ink)});X.fillStyle=[hot,cold,acid][i%3];X.beginPath();X.arc(n.x*w,n.y*h,n.s,0,7);X.fill();label(i%4?'N_'+i.toString(16):'SIN PERFIL',n.x*w+n.s,n.y*h,8,ink)});
 if(scene===4)wins.forEach((q,i)=>{if(!paused){q.x+=q.v;if(q.x<-.25)q.x=1;if(q.x>1)q.x=-.25}const x=q.x*w,y=q.y*h,ww=q.w*w,hh=q.h*h;X.fillStyle=i%3?bg:acid;X.strokeStyle=[ink,hot,cold][i%3];X.lineWidth=2+i%4;X.fillRect(x,y,ww,hh);X.strokeRect(x,y,ww,hh);label('proc_'+i+' × □ _',x+4,y+11,7,X.strokeStyle);label(TEXTS[(i+mut)%TEXTS.length].slice(0,30),x+7,y+31,8+i%6,X.strokeStyle)});
 if(scene===5){for(let ring=0;ring<17;ring++){X.strokeStyle=[ink,hot,cold][ring%3];X.beginPath();for(let a=0;a<=Math.PI*2;a+=.08){const rad=25+ring*18+Math.sin(a*5+t+ring)*13,x=pointer.x*w+Math.cos(a)*rad*1.8,y=pointer.y*h+Math.sin(a)*rad;a?X.lineTo(x,y):X.moveTo(x,y)}X.stroke()}for(let i=0;i<32;i++){const x=(i*97+t*21)%w,y=(i*53+Math.sin(t+i)*80+h)%h;arrow(x,y,x+Math.sin(i)*40,y-25-i%5*7,[hot,cold,acid][i%3])}}
 if(scene===6){const meme=TEXTS[(Math.floor(t/2.4)+mut)%TEXTS.length];X.save();X.translate(w/2,h/2);X.rotate(Math.sin(t*.4)*.08);X.textAlign='center';X.font=`1000 ${Math.min(w/Math.max(4,meme.length*.42),h*.24)}px Arial Black`;X.lineWidth=12;X.strokeStyle=ink;X.fillStyle=hot;X.strokeText(meme,0,0,w*.9);X.fillText(meme,0,0,w*.9);X.restore()}
 if(scene===7){const r=seeded(Math.floor(t*1.7)+':'+mut);for(let i=0;i<58;i++){const x=r()*w,y=(r()*h+t*(8+i%12))%(h+180)-90,ww=12+r()*w*.18,hh=8+r()*h*.09;X.strokeStyle=[ink,hot,cold,acid][i%4];X.lineWidth=1+i%4;i%3?X.strokeRect(x,y,ww,hh):X.fillRect(x,y,ww,hh);if(i%4===0)arrow(x,y,x+(r()-.5)*200,y+80+r()*180,X.strokeStyle)}}
 X.globalAlpha=.14;X.fillStyle=ink;for(let i=0;i<160;i++)X.fillRect(Math.random()*w,Math.random()*h,1,1);X.globalAlpha=1;requestAnimationFrame(draw)}
SCENES.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML=String(i+1).padStart(2,'0')+'<span>'+s[0]+'</span>';b.onclick=()=>go(i);document.querySelector('#nav').append(b)});document.querySelector('#next').onclick=()=>go();document.querySelector('#pause').onclick=()=>{paused=!paused;restart();ui()};addEventListener('resize',resize);addEventListener('pointermove',e=>{pointer.x=e.clientX/innerWidth;pointer.y=e.clientY/innerHeight;pointer.energy=Math.min(1,pointer.energy+.12);M.style.setProperty('--px',e.clientX+'px');M.style.setProperty('--py',e.clientY+'px')});M.addEventListener('wheel',e=>{e.preventDefault();tempo=Math.max(3500,Math.min(18000,tempo+Math.sign(e.deltaY)*900));mut++;restart();ui()},{passive:false});addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();document.querySelector('#pause').click()}if(e.key==='ArrowRight'||e.key.toLowerCase()==='n')go();if(e.key.toLowerCase()==='c'){palette=Math.floor(Math.random()*8);applyPalette();ui()}if(e.key.toLowerCase()==='r'){mut++;makeSystem();makeWords();ui()}if(e.key.toLowerCase()==='p')print()});palette=Math.floor(Math.random()*8);applyPalette();makeSystem();makeWords();resize();ui();restart();requestAnimationFrame(draw);
